### ISSUE TITLE
Tick marker labeles not rendering in framebuffer mode (Avalonia)

### ISSUE THREAD

**Issue by eldendiss** [ScottPlot/ScottPlot#3392] opened 2024-02-20 14:27 UTC
**Issue:** 
After updating to version 5, the axis tick markers labels disappeared. I'm using custom linux distro (Yocto project), with avalonia running in framebuffer mode. The scatter data are being plotted and I'm able to pan and resize the plot just fine, however the tick labels remain hidden.

The exact same version however works on windows as seen in provided PNG figures.

Everything worked well in version 4 (except for the workaround needed for linux).

My suspicion is something being wrong with SkiaSharp, however its weird that some parts are rendered and some not. Also other plotting libraries using Skia, like livecharts2 are working in my environment (these are however too much stylish for me and not suited for precise plots).

**ScottPlot Version:** 5.0.21

**Code Sample:** 

```cs
avaPlot1 = this.Find<AvaPlot>("AvaPlot");
avaPlot1.Plot.Style.Background(ScottPlot.Color.FromHex("#2C3E50"), ScottPlot.Color.FromHex("#2C3E50"));
avaPlot1.Plot.Style.ColorAxes(ScottPlot.Color.FromHex("#ECF0F1"));

var xAxis = avaPlot1.Plot.Axes.DateTimeTicksBottom();
xAxis.TickLabelStyle.FontSize = 15;
xAxis.TickGenerator.MaxTickCount = 5;
xAxis.TickLabelStyle.FontSize = 15;
xAxis.Color(ScottPlot.Color.FromHex("#ECF0F1"));

var yAxis = avaPlot1.Plot.Axes.Left;
yAxis.TickLabelStyle.FontSize = 15;
yAxis.TickGenerator.MaxTickCount = 10;
yAxis.MinorTickStyle.Color = ScottPlot.Colors.Transparent;

var grid = avaPlot1.Plot.GetDefaultGrid();
grid.MajorLineStyle.Pattern = LinePattern.Dotted;
grid.MajorLineStyle.Color = ScottPlot.Color.FromHex("#ECF0F1");

avaPlot1.Refresh();
```

On linux: (in DRM mode)
![Plot](https://github.com/ScottPlot/ScottPlot/assets/17549538/7a5520a7-1d18-4e62-8972-a7bd55f3090e)

On windows:
![Plot_win](https://github.com/ScottPlot/ScottPlot/assets/17549538/f1ab4cc5-08cd-4dc1-bae9-7fb25c6da4b1)

**Comment by eldendiss** [comment] 2024-02-20 15:30
Nvm, found the issue.
ScottPlot does not use font specified by FontManagerOptions, and the default font is not present on my system, therefore it couldn't show any text.
Specifying font with `avaPlot1.Plot.Style.SetFont("Liberation Sans");` fixes this issue.

I will keep this open, so the maintainers can decide if this is a bug or not.

**Comment by swharden** [comment] 2024-03-16 22:12
Hi @eldendiss, thanks for reporting this issue and following-up with the fix! It seems the default font detection on Linux isn't working as well as expected. Unfortunately it's hard for me to troubleshoot this issue since I can't reproduce it on my system. If you decide to look deeper into it, I appreciate learning what you discover!

These lines of code set the default font:
https://github.com/ScottPlot/ScottPlot/blob/fdd1dfdf0fd8d32ce3176337c2140f5f14e44a20/src/ScottPlot5/ScottPlot5/Fonts.cs#L48-L62

I'm curious what the name of your default font is, and whether `SKTypeface.Default.FamilyName` is returning a bad font that can't be rendered or something.

I'll close this issue for now, but we can re-open it if we learn something that can support an action to fix this issue 👍

**Closed by swharden** 2024-03-16 22:12 UTC
