### ISSUE TITLE
ScottPlot5 crashes Visual Studio Designer for WinForms projects targeting .NET Framework

### ISSUE THREAD

**Issue by YNBTools** [ScottPlot/ScottPlot#2491] opened 2023-03-15 10:06 UTC
Error initializing  when adding scottplot.winforms.formsplot control to the Form

![Snipaste_2023-03-15_17-49-05](https://user-images.githubusercontent.com/32679861/225276583-7f76d613-6d0c-4402-bd59-6552bfffd993.jpg)

Is this caused by the initialization of ScottPlot.FontService?

### System Details
* **ScottPlot Version:** 5.02
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** NET Framework 4.8

**Comment by YNBTools** [comment] 2023-03-16 02:04
When added with code, it is OK
`public partial class Form1 : Form
    {
        readonly FormsPlot formsPlot1;
        public Form1()
        {
            InitializeComponent();
            formsPlot1=new FormsPlot { Dock= DockStyle.Fill };
            splitContainer1.Panel2.Controls.Add(formsPlot1);
        }     
    }`
![Snipaste_2023-03-16_10-04-08](https://user-images.githubusercontent.com/32679861/225490822-ea2cf334-c33e-4bc4-9309-5d08cb8f0053.jpg)

but
The above error occurs when using the designer

**Comment by swharden** [comment] 2023-03-31 01:38
Hi @YNBTools, thanks for reporting this!

It looks similar to the issue described here:
* https://github.com/mono/SkiaSharp/issues/1983
* https://github.com/mono/SkiaSharp/issues/572

The SkiaSharp maintainer wrote:
> I have recently worked a bit on the targets and the library to get them to work far better with .NET Framework.
However, I am not sure if there is a way to reliably and generically load the libSkiaSharp.dll from the NuGet package - for the designer. The good thing is that it works with the .NET Core designer.

Maybe the best solution here is to disable the preview on .NET Framework (or wrap it in a try block?) ... I'll look into it further and report back shortly

**Comment by swharden** [comment] 2023-03-31 02:04
Wow, I worked on this a lot and still did not reach a good solution... I think this is a bug related to SkiaSharp, VisualStudio, and designer mode for projects which multi-target .NET Framework and .NET Core

I was able to reproduce a similar error though:

```
[22:02:59.031008] fail: [Sandbox.WinForms_NET462]: Failed to load assembly: \\?\C:\Users\scott\AppData\Local\Microsoft\VisualStudio\17.0_c5f5d3be\WinFormsDesigner\bz2akuvd.zaj\UserAppData\libSkiaSharp.dll
                        System.BadImageFormatException: Bad IL format. The format of the file '\\?\C:\Users\scott\AppData\Local\Microsoft\VisualStudio\17.0_c5f5d3be\WinFormsDesigner\bz2akuvd.zaj\UserAppData\libSkiaSharp.dll' is invalid.
                           at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
                           at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
                           at Microsoft.DotNet.DesignTools.Services.TypeResolutionService.LoadFromAssemblyPath(String filePath)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[22:02:59.034007] fail: [Sandbox.WinForms_NET462]: Failed to launch design tools server process process
                        System.BadImageFormatException: Could not load file or assembly '\\?\C:\Users\scott\AppData\Local\Microsoft\VisualStudio\17.0_c5f5d3be\WinFormsDesigner\bz2akuvd.zaj\UserAppData\libSkiaSharp.dll'. The module was expected to contain an assembly manifest.
                        File name: '\\?\C:\Users\scott\AppData\Local\Microsoft\VisualStudio\17.0_c5f5d3be\WinFormsDesigner\bz2akuvd.zaj\UserAppData\libSkiaSharp.dll'
                           at System.Reflection.AssemblyName.nGetFileInformation(String s)
                           at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
                           at Microsoft.DotNet.DesignTools.Services.TypeResolutionService.LoadFromAssemblyPath(String filePath)
                           at Microsoft.DotNet.DesignTools.Services.TypeResolutionService.ProcessServerManifest()
                           at Microsoft.DotNet.DesignTools.Services.TypeResolutionService.EnqueueInitialAssemblies()
                           at Microsoft.DotNet.DesignTools.Services.TypeResolutionService..ctor(ILoggerFactory loggerFactory, GlobalObjectService globalObjectService, ServerManifest serverManifest, Boolean autoStartProcessing)
                           at Microsoft.DotNet.DesignTools.Services.GlobalServiceProvider.AddDefaultServices(ILoggerFactory loggerFactory, ServerManifest serverManifest, FrameworkName frameworkName)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.StartUpAsync(CancellationToken cancellationToken)
                           at Microsoft.DotNet.DesignTools.Server.DesignToolsServer.StartListeningAsync(Stream stream, TraceListener traceListener)
                           at Microsoft.DotNet.DesignTools.Server.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext()

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[22:02:59.039018] fail: Microsoft.DotNet.DesignTools.Client.ServerException: Failed to launch the design tools server process.
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.VisualStudio.Threading.TplExtensions.<WithTimeout>d__5.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<LaunchAsync>d__28.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__8.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__29.MoveNext()

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[22:02:59.134981] warn: Cannot update selection in server process as Session is not connected.
```

**Comment by swharden** [comment] 2023-03-31 02:16
These Visual Studio designer errors are extremely difficult to troubleshoot... I'm tempted to make ScottPlot 5 only support the currently supported versions of .NET Core 👿

ScottPlot 4 works great, and it will always run on .NET Framework, so users on .NET Framework should probably use that.

I'll close this issue now because I don't want to lose more time on it, and probably the official recommendation for now is that .NET Framework users should stick to ScottPlot 4 (or add the control programmatically). It's a dissatisfying "solution", but I'm struggling to think of a better option. I think at its core this is a SkiaSharp/VisualStudio issue I cannot easily fix 🤷

**Comment by swharden** [comment] 2023-03-31 03:59
@bclehmann suggested targeting only x86 or x64 instead of AnyCPU

I'll give that a try and report back when I do

**Comment by swharden** [comment] 2023-04-02 00:06
After looking further into it, it seems that SkiaSharp's DLL just does not operate reliably in the Visual Studio designer for .NET Framework projects, and there's not much I can do to fix it.

I think I can improve this issue by intentionally throwing an exception 🔥😈 

At least I will be able to provide a descriptive error message indicating what the problem is and how to fix it (adding the control programmatically or using .NET Core), and it will be more helpful than getting a "Bad IL format" error from SkiaSharp

**Comment by swharden** [comment] 2023-04-02 00:27
I uncovered what I think is a related bug that only applies to .NET Framework projects (this is thrown by the VS designer):

![image](https://user-images.githubusercontent.com/4165489/229324013-9b56c7b6-0e1c-43d0-a470-36a70da01c07.png)

**Comment by swharden** [comment] 2023-04-02 02:05
I spent a lot more time looking into this... and I am going to make the difficult decision to put this down now without a good solution 😩 

Conclusions:
* This is a SkiaSharp + VS Designer issue (largely out of my control)
* ScottPlot 5 works in the _builds_, just not inside Visual studio
* Crashing is prevented by adding the control programmatically
* My preferred action here is to do nothing. These messages are searchable and will lead here.
* The second best option is to drop support for .NET Framework in ScottPlot 5 (but that feels too extreme)

**Closed by swharden** 2023-04-02 02:05 UTC
Labels: BUG

**Comment by CoderPM2011** [comment] 2024-09-04 15:42
> I spent a lot more time looking into this... and I am going to make the difficult decision to put this down now without a good solution 😩
> 
> Conclusions:
> 
> * This is a SkiaSharp + VS Designer issue (largely out of my control)
> * ScottPlot 5 works in the _builds_, just not inside Visual studio
> * Crashing is prevented by adding the control programmatically
> * My preferred action here is to do nothing. These messages are searchable and will lead here.
> * The second best option is to drop support for .NET Framework in ScottPlot 5 (but that feels too extreme)

If you adopt the implementation method mentioned in https://github.com/mono/SkiaSharp/issues/2110
when `designMode==true`, do not call any `SkiaSharp` functions.
You should be able to avoid this problem, but it will be like #2762

---

By the way
I accidentally discovered something interesting today.🤔

Under `WIN10`, 
if I put the corresponding `libSkiaSharp.dll` in the corresponding path in the solution folder, 
VS Designer can read `libSkiaSharp.dll`, but this is not a good solution😥
![image](https://github.com/user-attachments/assets/2f6ad855-d913-4bff-8765-7cf9b5cae2fa)

**Comment by ck888w** [comment] 2024-09-15 12:31
CoderPM2011 provides "A" solution even it may not be an elegant, I can try it until a long term solution is available. I will report after I do the following:
1. move the dll to the corresponding directory
2. set the target specific, in my case it will be x64.

**Comment by ck888w** [comment] 2024-09-15 13:19
Just tried and it works. No more crash when I drop the FormPlot to the WinForm. The DLL is copied from the directory of 
...\packages\SkiaSharp.NativeAssets.Win32.2.88.8\runtimes\win-x86\native
and
packages\SkiaSharp.NativeAssets.Win32.2.88.8\runtimes\win-x64\native

The following is the directory tree:

![image](https://github.com/user-attachments/assets/8b5ca879-cea1-41cf-8cd0-ea05aedfe7d1)

I can now continue my learning journey and report any coding/development/deployment discover.

Thank you for your helps.

**Comment by FrankBolleri** [comment] 2024-10-19 23:17
> Just tried and it works. No more crash when I drop the FormPlot to the WinForm. The DLL is copied from the directory of ...\packages\SkiaSharp.NativeAssets.Win32.2.88.8\runtimes\win-x86\native and packages\SkiaSharp.NativeAssets.Win32.2.88.8\runtimes\win-x64\native
> 
> The following is the directory tree:
> 
> ![image](https://private-user-images.githubusercontent.com/46503132/367583984-8b5ca879-cea1-41cf-8cd0-ea05aedfe7d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNzg4MDIsIm5iZiI6MTcyOTM3ODUwMiwicGF0aCI6Ii80NjUwMzEzMi8zNjc1ODM5ODQtOGI1Y2E4NzktY2VhMS00MWNmLThjZDAtZWEwNWFlZGZlN2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDIyNTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTQwYjExZjRkNDY1Nzk4MWZmMGMxNDIwOWRkOTQ1ZDY1ZmNlODdlNDQ5NzJhNTc1NGEzNGViOGE1NzUxYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8MKXkfxyNamdCyQ_9Ka74xGXwzHB6vbrGViAZdSqLY4)
> 
> I can now continue my learning journey and report any coding/development/deployment discover.
> 
> Thank you for your helps.

Hello all, I confirm the workaround works.
Just I think should be useful to specify that, if you are in the case of **Solution** not in the same folder of the **Project** the correct placement of the two folders x64 and x86 seems to be the **Solution folder**.
![Screenshot 2024-10-20 at 01 16 44](https://github.com/user-attachments/assets/adb1ac48-6c8e-4457-a225-82d8f34235b8)
