### ISSUE TITLE
Legend text rtl support

### ISSUE THREAD

**Issue by moranmono** [ScottPlot/ScottPlot#4306] opened 2024-10-07 16:17 UTC
**Question:** Hi, I have searched through the open and closed issues as well as discussions, but I couldn't find any mention of right-to-left (RTL) support for legend text. I understand that ScottPlot currently does not support RTL for legend text. Is this something that is planned?

**ScottPlot Version:** version 5.0.39

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples
```cs
private LegendItem CreateLegendItem(string legendText, Color color)
        {
            return new LegendItem()
            {
                LabelText = legendText,
                MarkerLineColor = color,
                LineColor = color,
                LineWidth = 3,
            };
        }
```

**Comment by StendProg** [comment] 2024-10-07 17:18
Hi @moranmono,

I am totally unfamiliar with RTL languages, please forgive my ignorance.
As far as I understand, Arabic is displayed correctly, but in reverse left to right form?
And you want this reversal to be done automatically?
A little research led me to the conclusion that it is not that difficult to do in SkiaSharp.

To do this we need to add a dependency of the main project on the `SkiaSharp.HarfBuzz` package.
After that, we need to replace all calls to` Canvas.DrawText(....)` with something like this 
```c#
using (var tf = SKFontManager.Default.MatchCharacter('א'))
using (var shaper = new SKShaper(tf))
canvas.DrawShapedText(shaper, ....)
```
There could still be issues with MeasureText methods, maybe they would require a special wrapper too, I haven't investigated here.

Anyway, this is a big enough architectural change that it may not be accepted, I just shared what I found.

**Comment by moranmono** [comment] 2024-10-08 07:34
Hi. 
Thank you for the quick response. Yes, in my case, the Hebrew letters appear OK, but the order is reversed. I am not looking for an automatic solution; I know it could lead to a major change and will take a lot of time. 
I already know the culture that my client is using; I have several clients in several different languages, so maybe you could add a flag of some sort, like this ex: 
```cs
sig1.LegendText = "אמת";
WpfPlot1.Plot.Legend.FontSize = 40;
WpfPlot1.Plot.Legend.IsRTL = true;
WpfPlot1.Plot.ShowLegend();
```

**Comment by StendProg** [comment] 2024-10-09 16:03
In fact, the solution turned out to be quite simple. The static field looks ridiculous, but it does what it's supposed to do. The problem is an additional dependency on `SkiaSharp.HarfBuzz`. `ScottPlot` really avoids adding dependencies.

You can look up/use my solution if you need it urgently and are not put off by building your own nuget packages.
https://github.com/StendProg/ScottPlot/tree/RTLSupport

This solution should add RTL support to absolutely all labels used by ScottPlot, not just the legend.
I can't test it because I don't know RTL languages.
```c#
        LabelStyle.RTLSupport = true;
        var sig1 = WpfPlot1.Plot.Add.Signal(ScottPlot.Generate.Sin());
        var sig2 = WpfPlot1.Plot.Add.Signal(ScottPlot.Generate.Cos());
        sig1.LegendText = "אמת";
        sig2.LegendText = "Engish";
        WpfPlot1.Plot.Legend.FontSize = 40;
        WpfPlot1.Plot.ShowLegend();

```

**Comment by moranmono** [comment] 2024-10-09 16:49
Excellent, thank you. 
So, should this feature be in the next release?

**Comment by moranmono** [comment] 2024-10-10 05:50
Thank you. Please let me know if you include this feature in the product. This will be an excellent addition for me.

**Comment by swharden** [comment] 2024-11-08 21:29
Hi @moranmono and @StendProg, thank you for this interesting discussion!

> To do this we need to add a dependency of the main project on the SkiaSharp.HarfBuzz package

It's a packaged owned by Microsoft, so I wouldn't object to it https://www.nuget.org/packages/SkiaSharp.HarfBuzz/

> we need to replace all calls to Canvas.DrawText(....)

That sounds like a lot of work, but if it could improve international font support (a topic which keep coming up) it may be worth considering. Since most text rendering and measurement happens in the `ScottPlot.Drawing` class, perhaps the number of changed files would be very minimal?

> I haven't investigated here

I have a graphical test runner that lets me compare two folders of cookbook images to see their "diffs" and identify if/where a change to the code affects rendering. It may be pretty easy to make changes here and be confident nothing major is breaking.

![image](https://github.com/user-attachments/assets/9619f000-abcc-4d19-84c9-c008a45b952a)

![diff3](https://github.com/ScottPlot/ScottPlot/assets/4165489/bd557310-8ac8-42a4-998f-a1b5718e6e2a)

I'll close this issue for now since there isn't active movement on it, but if someone wants to create a pull request (ideally with a minimum number of modified files) I'd be happy to review it!

**ALTERNATIVE:** Perhaps we could create a demo app that uses `HarfBuzz` to create custom text as a bitmap then use the image in legends or for labels elsewhere in ScottPlot. That would not only solve this issue, but be a possible strategy for supporting richer text like RTF and HTML.

**Closed by swharden** 2024-11-08 21:29 UTC

**Comment by moranmono** [comment] 2024-11-12 12:42
@StendProg @swharden 
If there is no objection, @StendProg Can you create a PR from the branch you have created?
