### ISSUE TITLE
plt.SetAxisLimits don't work well if i set plt.XAxis.TickLabelStyle simultaneously

### ISSUE THREAD

**Issue by uamhforever** [ScottPlot/ScottPlot#1801] opened 2022-04-25 12:56 UTC
---------------------------------

## Bug Report

**Issue:** 
plt.SetAxisLimits don't work well if i set plt.XAxis.TickLabelStyle simultaneously

**Reproducing:**
plt.XAxis's AxisLimits and MinimumTickSpacing can't work, but plt.XAxis2 can work well
```cs
plt.XAxis.MinimumTickSpacing(MaxValue / 10.0);
plt.SetAxisLimits(0, MaxValue);
// plt.XAxis.TickLabelStyle(fontSize: 28, fontBold: false);

plt.XAxis2.Ticks(true);
plt.XAxis2.MinimumTickSpacing(0.1);
plt.SetAxisLimits(0, 1.0, xAxisIndex: 1);
plt.XAxis2.LabelStyle(fontSize: 28);
plt.XAxis2.TickLabelStyle(fontSize: 28, fontBold: false);
```

### System Details
* **ScottPlot Version:** 4.1.41
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** NET 6.0

**Comment by uamhforever** [comment] 2022-04-25 13:28
another code like this：
MinimumTickSpacing can't work

```cs
public MainViewModel()
        {
            _myPlot1 = new WpfPlot();
            _myPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.High;

            Plot plt = new ScottPlot.Plot(240, 180);

            Random rnd = new Random();
            List<double> xdatas = new List<double>();
            List<double> ydatas = new List<double>();
            for (int i = 0; i < 21; i++)
            {
                xdatas.Add(i / 20.0);
                ydatas.Add(rnd.NextDouble());
            }

            double[] xs = DataGen.Consecutive(51);
            double[] sin = DataGen.Sin(51);

            ScatterPlot splt = plt.AddScatter(xs, sin);

            ScatterPlot splt2 = plt.AddScatter(xdatas.ToArray(), ydatas.ToArray());
            splt2.XAxisIndex = 1;

            plt.XAxis.MinimumTickSpacing(5);
            plt.SetAxisLimits(0, 100);
            plt.XAxis.TickLabelStyle(fontSize: 28, fontBold: false);

            plt.XAxis2.Ticks(true);
            plt.XAxis2.MinimumTickSpacing(0.1);
            plt.SetAxisLimits(0, 1.0, xAxisIndex: 1);
            plt.XAxis2.LabelStyle(fontSize: 28);
            plt.XAxis2.TickLabelStyle(fontSize: 28, fontBold: false);

            plt.Title("Test", bold: true, Color.Black, size: 32, fontName: "Consolas");
            plt.XAxis.Label("X Axis", Color.Black, size: 28, bold: true);
            plt.YAxis.Label("Y Axis", Color.Black, size: 28, bold: true);

            plt.YAxis.TickLabelStyle(fontSize: 28, fontBold: false);

            _myPlot1.Reset(plt);
            _myPlot1.Refresh();
        }

        private WpfPlot _myPlot1;
```

**Comment by uamhforever** [comment] 2022-04-25 13:37
> a complete demo code like this： AxisLimits & MinimumTickSpacing can't work
> 
> ```cs
> using System;
> using System.Collections.Generic;
> using System.Drawing;
> using System.Linq;
> using ScottPlot;
> using ScottPlot.Plottable;
> using WpfDemo.Base;
> 
> namespace WpfDemo.ViewModels
> {
> 
>     public  class MainViewModel : ViewModelBase
>     {
>         public MainViewModel()
>         {
>             _myPlot1 = new WpfPlot();
>             _myPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.High;
> 
>             Plot plt = new ScottPlot.Plot(240, 180);
> 
>             Random rnd = new Random();
>             List<double> xdatas = new List<double>();
>             List<double> ydatas = new List<double>();
>             for (int i = 0; i < 21; i++)
>             {
>                 xdatas.Add(i / 20.0);
>                 ydatas.Add(rnd.NextDouble());
>             }
> 
>             double[] xs = DataGen.Consecutive(66);
>             double[] sin = DataGen.Sin(66);
> 
>             ScatterPlot splt = plt.AddScatter(xs, sin);
> 
>             ScatterPlot splt2 = plt.AddScatter(xdatas.ToArray(), ydatas.ToArray());
>             splt2.XAxisIndex = 1;
> 
>             plt.XAxis.MinimumTickSpacing(5);
>             plt.SetAxisLimits(0, 65);
>             plt.XAxis.TickLabelStyle(fontSize: 28, fontBold: false);
> 
>             plt.XAxis2.Ticks(true);
>             plt.XAxis2.MinimumTickSpacing(0.1);
>             plt.SetAxisLimits(0, 1.0, xAxisIndex: 1);
>             plt.XAxis2.LabelStyle(fontSize: 28);
>             plt.XAxis2.TickLabelStyle(fontSize: 28, fontBold: false);
> 
>             plt.Title("Test", bold: true, Color.Black, size: 32, fontName: "Consolas");
>             plt.XAxis.Label("X Axis", Color.Black, size: 28, bold: true);
>             plt.YAxis.Label("Y Axis", Color.Black, size: 28, bold: true);
> 
>             plt.YAxis.TickLabelStyle(fontSize: 28, fontBold: false);
> 
>             _myPlot1.Reset(plt);
>             _myPlot1.Refresh();
>         }
> 
>         private WpfPlot _myPlot1;
>         public WpfPlot MyPlot1
>         {
>             get { return _myPlot1; }
>             set
>             {
>                 _myPlot1 = value;
>                 OnPropertyChanged("MyPlot1");
>             }
>         }
>     }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/53807302/165099882-09819f76-d6cb-4d8a-84bb-2a45ffbb4e1e.png)
if i comment this line
```cs
plt.XAxis.TickLabelStyle(fontSize: 28, fontBold: false);
```
AxisLimits & MinimumTickSpacing will work

**Comment by swharden** [comment] 2022-05-01 15:13
Hi @uamhforever, 

Thank you for opening this issue and sharing your code and example output.

Unfortunately I am struggling to understand exactly what the problem is. You say "SetAxisLimits don't work well", but what does this mean? What indication is there that it is not working well?

This is the test I am using to try to demonstrate a problem. The output looks good to me whether the `TickLabelStyle()` is commented-out or not. Can this test be modified to demonstrate the issue you describe?


```cs
[Test]
public void Test_TickStyle_1801()
{
    var plt = new ScottPlot.Plot(900, 300);

    var scatter1 = plt.AddScatter(
        xs: ScottPlot.DataGen.Consecutive(100, spacing: .05),
        ys: ScottPlot.DataGen.Sin(100));

    var scatter2 = plt.AddScatter(
        xs: ScottPlot.DataGen.Consecutive(100, spacing: 1),
        ys: ScottPlot.DataGen.Cos(100));
    scatter2.XAxisIndex = 1;

    plt.XAxis.MinimumTickSpacing(2);
    plt.SetAxisLimits(0, 7);
    plt.XAxis.TickLabelStyle(fontSize: 16); // <-- THIS LINE

    plt.XAxis2.Ticks(true);
    plt.XAxis2.MinimumTickSpacing(50);
    plt.SetAxisLimits(0, 120, xAxisIndex: 1);
    plt.XAxis2.TickLabelStyle(fontSize: 16);

    TestTools.SaveFig(plt);
}
```

### With TickLabelStyle()
![image](https://user-images.githubusercontent.com/4165489/166152209-c145fba1-8027-428a-b192-e8e650d7f4f3.png)

### Without TickLabelStyle()
![image](https://user-images.githubusercontent.com/4165489/166152226-9658f5d1-760c-4895-87c9-05055886a35f.png)

---

I'm going to close this issue for now since I can't understand what the problem is, but feel free to open it again if you have additional information I can use to help arrive at a solution 👍

**Closed by swharden** 2022-05-01 15:13 UTC
Labels: BUG

**Comment by swharden** [comment] 2022-05-01 15:16
Also, note the definition of "minimum tick spacing".

If you set this to 5, it means that ticks will never be closer than 5 units apart. 

It does _not_ mean that all ticks will be 5 units apart.

If you want to define exactly how close ticks are together, that is possible using `ManualTickSpacing()` https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#defined-tick-spacing

**Comment by uamhforever** [comment] 2022-05-07 02:02
Actually i test your code, and when i zoom the plot then zoom to fit data, the plot's AxisLimits will not be exactly be (0, 7, xAxisIndex: 0) and (0, 120, xAxisIndex: 1),how can i solve this probel
![ScottPlot](https://user-images.githubusercontent.com/53807302/167233581-72d4bf78-580b-4459-8c50-03e526d7b1eb.png)
m

**Comment by swharden** [comment] 2022-05-07 12:07
Hi @uamhforever,

Calling `AxisAuto()` will adjust the axis limits to fit the data with padding on all sides. Set the `horizontalMargin` and `verticalMargin` arguments to `0` if you want the axis limits to tightly fit the data.
