### ISSUE TITLE
InvalidOperationException when zooming/panning a SignalXY plot with large amount of data points

### ISSUE THREAD

**Issue by Niravk1997** [ScottPlot/ScottPlot#1808] opened 2022-04-28 02:04 UTC
## Bug Report

**Issue:** An InvalidOperationException occurs when zooming/panning a SignalXY plot containing large amount of data points.

**Reproducing:** Just plot a SignalXY plot containing large amount of data and start zooming and panning. The description of the exception shows 'Data must not contain NAN' but I checked and my data does not contain NAN. This exception could take a while to occur depending of how you zoom/pan the plot. In the video, I plotted an 8 million data points SignalXY plot.

### System Details
* **ScottPlot Version:** 4.1.41
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** NET Framework 4.7.2

https://user-images.githubusercontent.com/52579388/165659940-1a6ab5a7-35b4-4fe3-b49a-e86793b7a2bd.mp4

I have attached the source code for an application that will load the data from a text file and plot a SignalXY plot. It is a 7zip file, I renamed it to zip because github doesn't allow uploading of 7zip files. It contains a simple project and a waveform text file, as show in the video.
[Bug_Demo_src_7zip_file.zip](https://github.com/ScottPlot/ScottPlot/files/8578955/Bug_Demo_src_7zip_file.zip)

**Comment by StendProg** [comment] 2022-04-28 18:03
Hi @Niravk1997,

The problem arises not in the data, but in the points for rendering. It looks like the problem is the same as in #1803.
Only in your case, the points are the same not only in x but also in y. Therefore, during interpolation, [0/0] occurs, the result of which is NaN.
The #1806 fix should help, but your test case is very hard to reproduce bug. Sometimes I can throw an exception in a few seconds, sometimes I spend a few minutes moving the chart and close it out of desperation. I tested this fix on several bad positives and didn't get an exception.

**Comment by swharden** [comment] 2022-05-01 15:20
Hi @Niravk1997, thank you for reporting this (with video!)

I agree that this was probably due to #1803 and was likely fixed in #1806. 

I'm going to publish a NuGet package today (version 4.1.42) and close this issue assuming it will fix this problem, but if not we can open this up again and take a closer look 👍

**Closed by swharden** 2022-05-01 15:20 UTC
Labels: BUG
