### ISSUE TITLE
Axis line position labels should move out of the way instead of overlapping

### ISSUE THREAD

**Issue by hamhub7** [ScottPlot/ScottPlot#1972] opened 2022-07-21 19:42 UTC
## Feature Suggestion

**Feature description:** 
When using multiple axis lines, especially when draggable by the user, their position labels can end up overlapping each other. The suggested feature would be an option that could be turned on in the axis line that would cause its label to move out of the way when overlapping with another axis label.
**Code example:** 

```cs
var plt = new ScottPlot.Plot();
plt.AddSignal(DataGen.Sin(51));

var vline1 = plt.AddVerticalLine(23);
vline1.LineWidth = 2;
vline1.PositionLabel = true;
vline1.PositionLabelBackground = vline.Color;
vline1.DragEnabled = true;
vline1.PositionLabelOverlap = false;

var vline2 = plt.AddVerticalLine(24);
vline2.LineWidth = 2;
vline2.PositionLabel = true;
vline2.PositionLabelBackground = vline.Color;
vline2.DragEnabled = true;
vline2.PositionLabelOverlap = false;
```
The resulting plot would have two labels sitting side-by-side instead of partially overlapped

**Comment by swharden** [comment] 2022-08-04 00:45
Hi @hamhub7, thanks for the suggestion! I created the following program to better demonstrate the issue

```cs
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.AddSignal(DataGen.Sin(51), 1, Color.Black) ;

        var vline1 = formsPlot1.Plot.AddVerticalLine(23, Color.Blue);
        vline1.LineWidth = 2;
        vline1.PositionLabel = true;
        vline1.DragEnabled = true;
        vline1.PositionLabelBackground = vline1.Color;

        var vline2 = formsPlot1.Plot.AddVerticalLine(24, Color.Red);
        vline2.LineWidth = 2;
        vline2.PositionLabel = true;
        vline2.DragEnabled = true;
        vline2.PositionLabelBackground = vline2.Color;

        formsPlot1.Refresh();
    }
}
```

![overlap](https://user-images.githubusercontent.com/4165489/182738979-5226d1d6-0619-42e0-bd43-48654d4fcdb2.gif)

The issue is that as the lines are dragged together, one label overlaps the other.

To be honest though, I can't think of a true fix for this. A partial fix could be adding a flag to customize the _alignment_ of the label. Left-aligned and right-aligned labels wouldn't overlap, but if you add a third line you'd experiencing overlap no matter what.

I'll see if I can implement basic alignment and demonstrate how to toggle it dynamically based on line position. I'll follow-up here with what I find! 👍

**Comment by swharden** [comment] 2022-08-05 01:23
I haven't decided on the final API, but I can add an option to customize alignment so people can do something like this 

![overlap2](https://user-images.githubusercontent.com/4165489/182981690-61bff712-e5a4-4e18-a7f4-f22ea7511f7e.gif)

The effect isn't awesome, but it works 🤔 

```cs
public partial class Form1 : Form
{
    ScottPlot.Plottable.VLine VLine1;
    ScottPlot.Plottable.VLine VLine2;

    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.AddSignal(DataGen.Sin(51), 1, Color.Black);
        formsPlot1.Plot.AddSignal(DataGen.Cos(51), 1, Color.Gray);

        VLine1 = formsPlot1.Plot.AddVerticalLine(23, Color.Blue);
        VLine1.LineWidth = 2;
        VLine1.PositionLabel = true;
        VLine1.DragEnabled = true;
        VLine1.PositionLabelBackground = VLine1.Color;
        VLine1.PositionLabelFont.Size = 16;

        VLine2 = formsPlot1.Plot.AddVerticalLine(24, Color.Red);
        VLine2.LineWidth = 2;
        VLine2.PositionLabel = true;
        VLine2.DragEnabled = true;
        VLine2.PositionLabelBackground = VLine2.Color;
        VLine2.PositionLabelFont.Size = 16;

        formsPlot1.PlottableDragged += FormsPlot1_PlottableDragged;

        formsPlot1.Refresh();
    }

    private void FormsPlot1_PlottableDragged(object sender, EventArgs e)
    {
        if (VLine1.X > VLine2.X)
        {
            VLine1.PositionLabelAlignmentX = ScottPlot.HorizontalAlignment.Left;
            VLine2.PositionLabelAlignmentX = ScottPlot.HorizontalAlignment.Right;
        }
        else
        {
            VLine1.PositionLabelAlignmentX = ScottPlot.HorizontalAlignment.Right;
            VLine2.PositionLabelAlignmentX = ScottPlot.HorizontalAlignment.Left;
        }
    }
}
```

**Comment by swharden** [comment] 2022-08-05 02:11
Okay I'm about to merge this in. I think it landed in an okay place.

![overlap3](https://user-images.githubusercontent.com/4165489/182986745-0bc1dcbb-1123-4cf7-8c9f-56692c7f385a.gif)

```cs
public partial class Form1 : Form
{
    ScottPlot.Plottable.VLine VLine1;
    ScottPlot.Plottable.VLine VLine2;
    ScottPlot.Plottable.HLine HLine1;
    ScottPlot.Plottable.HLine HLine2;

    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.AddSignal(DataGen.Sin(51), 1, Color.Black);
        formsPlot1.Plot.AddSignal(DataGen.Cos(51), 1, Color.Gray);

        VLine1 = formsPlot1.Plot.AddVerticalLine(23, Color.Blue);
        VLine1.LineWidth = 2;
        VLine1.PositionLabel = true;
        VLine1.DragEnabled = true;
        VLine1.PositionLabelBackground = VLine1.Color;
        VLine1.PositionLabelFont.Size = 16;

        VLine2 = formsPlot1.Plot.AddVerticalLine(24, Color.Red);
        VLine2.LineWidth = 2;
        VLine2.PositionLabel = true;
        VLine2.DragEnabled = true;
        VLine2.PositionLabelBackground = VLine2.Color;
        VLine2.PositionLabelFont.Size = 16;

        HLine1 = formsPlot1.Plot.AddHorizontalLine(.2, Color.Green);
        HLine1.DragEnabled = true;
        HLine1.PositionLabel = true;
        HLine1.PositionLabelBackground = HLine1.Color;

        HLine2 = formsPlot1.Plot.AddHorizontalLine(.4, Color.Orange);
        HLine2.DragEnabled = true;
        HLine2.PositionLabel = true;
        HLine2.PositionLabelBackground = HLine2.Color;

        formsPlot1.PlottableDragged += FormsPlot1_PlottableDragged;

        formsPlot1.Plot.Layout(right: 40);
        FormsPlot1_PlottableDragged(null, null);
        formsPlot1.Refresh();
    }

    private void FormsPlot1_PlottableDragged(object sender, EventArgs e)
    {
        if (VLine1.X > VLine2.X)
        {
            VLine1.PositionLabelAlignmentX = ScottPlot.HorizontalAlignment.Left;
            VLine2.PositionLabelAlignmentX = ScottPlot.HorizontalAlignment.Right;
        }
        else
        {
            VLine1.PositionLabelAlignmentX = ScottPlot.HorizontalAlignment.Right;
            VLine2.PositionLabelAlignmentX = ScottPlot.HorizontalAlignment.Left;
        }

        if (HLine1.Y > HLine2.Y)
        {
            HLine1.PositionLabelAlignmentY = ScottPlot.VerticalAlignment.Lower;
            HLine2.PositionLabelAlignmentY = ScottPlot.VerticalAlignment.Upper;
        }
        else
        {
            HLine1.PositionLabelAlignmentY = ScottPlot.VerticalAlignment.Upper;
            HLine2.PositionLabelAlignmentY = ScottPlot.VerticalAlignment.Lower;
        }
    }

    private void checkBox1_CheckedChanged(object sender, EventArgs e)
    {
        VLine1.PositionLabelOppositeAxis = checkBox1.Checked;
        VLine2.PositionLabelOppositeAxis = checkBox1.Checked;
        HLine1.PositionLabelOppositeAxis = checkBox1.Checked;
        HLine2.PositionLabelOppositeAxis = checkBox1.Checked;
        formsPlot1.Refresh();
    }
}
```

**Closed** 2022-08-05 03:23 UTC
