### ISSUE TITLE
Double left click does not show benchmark in WPF

### ISSUE THREAD

**Issue by onur-akaydin** [ScottPlot/ScottPlot#4524] opened 2024-11-16 19:09 UTC
**Issue:**
Just tried version 5.0.45 and realized that double left click does not show benchmark, both in my own code and in the ScottPlot WPF Demo.

It is working for WinForms. Triggering `UserInputProcessor.DoubleLeftClickBenchmark(true)` also does not help.

**ScottPlot Version:** 5.0.45

**Comment by swharden** [comment] 2024-11-16 21:18
> both in my own code and in the ScottPlot WPF Demo

It may be that many of the demo windows intentionally disable this feature.

I created a new .NET 8 WinForms project according to the directions in https://scottplot.net/quickstart/winforms/ and it works as expected. Maybe start there and confirm it works for you too?

**Comment by swharden** [comment] 2024-11-16 21:19
> It is working for WinForms

My bad, I just now realized this is specifically discussing WPF. Taking a closer look...

**Comment by swharden** [comment] 2024-11-16 21:30
It looks like the issue is here:
https://github.com/ScottPlot/ScottPlot/blob/11231f95d0caf55d3a2c5d60909e74fb3af95c67/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WPF/WpfPlot.cs#L46

After click 1 the focus is lost, resetting memory of the first click, then click 2 is treated like a single click

**Comment by swharden** [comment] 2024-11-16 21:36
Got it resolved! Thanks again for reporting this @onur-akaydin. That was a sneaky one to track down, but I'm happy to know that it will be fixed in the next release I intend to publish to NuGet tomorrow 🚀

**Closed** 2024-11-16 21:35 UTC
