### ISSUE TITLE
MutiAxis：HorizontalLine position label can‘t show in additional axis

### ISSUE THREAD

**Issue by fuxinsen** [ScottPlot/ScottPlot#1766] opened 2022-04-07 07:52 UTC
---------------------------------

**ScottPlot Version:** 4.1.39

**Operating System:** Windows 11 21H2

**Application Type:** WinForms

**Question:** I want to show position label in additional axis (YAxisIndex is above 1), but it only render in primary axis (YAxisIndex is 0). `HLine.YAxisIndex` and `SignalPlot.YAxisIndex` are set correctly.
![2022-04-07_15-26](https://user-images.githubusercontent.com/62933414/162144397-efdf8e05-dfb6-4b30-ab10-c64657e045b2.jpg)

the example code is modified from WinFormsDemos MultiAxisLock.

```cs
    public partial class MultiAxisLock : Form
    {
        private readonly ScottPlot.Renderable.Axis YAxis3;
        private readonly ScottPlot.Renderable.Axis YAxis4;

        public MultiAxisLock()
        {
            InitializeComponent();

            Random rand = new Random();
            double[] data1 = DataGen.RandomWalk(rand, 100, mult: 1);
            double[] data2 = DataGen.RandomWalk(rand, 100, mult: 10);
            double[] data3 = DataGen.RandomWalk(rand, 100, mult: 100);
            double avg1 = data1.Sum() / data1.Length;
            double avg2 = data2.Sum() / data2.Length;
            double avg3 = data3.Sum() / data3.Length;

            // Add signals specifying the vertical axis index for each
            var plt1 = formsPlot1.Plot.AddSignal(data1);
            plt1.YAxisIndex = 0;
            plt1.LineWidth = 3;
            plt1.Color = Color.Magenta;

            var plt2 = formsPlot1.Plot.AddSignal(data2);
            plt2.YAxisIndex = 3;
            plt2.LineWidth = 3;
            plt2.Color = Color.Green;

            var plt3 = formsPlot1.Plot.AddSignal(data3);
            plt3.YAxisIndex = 2;
            plt3.LineWidth = 3;
            plt3.Color = Color.Navy;

            // Add draggable horizontal lines specifying the vertical axis index for each
            var hline1 = formsPlot1.Plot.AddHorizontalLine(avg1);
            hline1.DragEnabled = true;
            hline1.Color = plt1.Color;
            hline1.LineStyle = LineStyle.Dash;
            hline1.YAxisIndex = 0;
            hline1.PositionLabelBackground = plt1.Color;
            hline1.PositionFormatter = (double position) => position.ToString("N0");
            hline1.PositionLabel = true;

            var hline3 = formsPlot1.Plot.AddHorizontalLine(avg3);
            hline3.DragEnabled = true;
            hline3.Color = plt3.Color;
            hline3.LineStyle = LineStyle.Dash;
            hline3.YAxisIndex = 2;
            hline3.PositionLabelBackground = plt3.Color;
            hline3.PositionFormatter = (double position) => position.ToString("N0");
            hline3.PositionLabel = true;

            var hline2 = formsPlot1.Plot.AddHorizontalLine(avg2);
            hline2.DragEnabled = true;
            hline2.Color = plt2.Color;
            hline2.LineStyle = LineStyle.Dash;
            hline2.YAxisIndex = 3;
            hline2.PositionLabelBackground = plt2.Color;
            hline2.PositionFormatter = (double position) => position.ToString("N0");
            hline2.PositionLabel = true;

            formsPlot1.Plot.YAxis.Color(Color.Magenta);

            // Create additional vertical axis and customize it
            YAxis3 = formsPlot1.Plot.AddAxis(Renderable.Edge.Left, 2);
            YAxis3.Color(Color.Navy);

            YAxis4 = formsPlot1.Plot.AddAxis(Renderable.Edge.Left, 3);
            YAxis4.Color(Color.Green);

            formsPlot1.Plot.AxisAuto();
            SetLocks();

            formsPlot1.Refresh();
        }

        private void SetLocks()
        {
            formsPlot1.Plot.YAxis.LockLimits(!cbPrimary.Checked);
            YAxis4.LockLimits(!cbSecondary.Checked);
            YAxis3.LockLimits(!cbTertiary.Checked);
        }

        private void cbPrimary_CheckedChanged(object sender, EventArgs e) => SetLocks();
        private void cbSecondary_CheckedChanged(object sender, EventArgs e) => SetLocks();
        private void cbTertiary_CheckedChanged(object sender, EventArgs e) => SetLocks();
    }

```

**Comment by swharden** [comment] 2022-04-07 13:00
Thanks for reporting this @fuxinsen! I added this feature in #1768 and will publish a new package on NuGet shortly.

The new workflow is to save the axes as you create them, then pass them into each horizontal line by assigning to their `` field.
```cs
var yAxis2 = formsPlot1.Plot.AddAxis(ScottPlot.Renderable.Edge.Left, 2);
var hline2 = formsPlot1.Plot.AddHorizontalLine(avg3);
hline2.YAxisIndex = 2;
hline2.PositionLabel = true;
hline2.PositionLabelAxis = yAxis2; // <-- like this
```

![1766](https://user-images.githubusercontent.com/4165489/162204573-fbe88158-c89d-4fea-9ad3-a16edd6b3752.gif)

**Comment by mengfanmin123** [comment] 2024-06-15 16:30
ScottPlot Version ：5.0.34
I also want to show the horizontalLine position label in additional axis. What should I do with  ScottPlot 5.

**Comment by swharden** [comment] 2024-06-15 18:21
Hi @mengfanmin123, I'll open up this issue to track progress toward adding this feature in ScottPlot 5

If you or someone from the open source community adds this feature before I'm able to look at it, I would be happy to review a pull request in good time! The code below is the place to modify to achieve the desired behavior 🚀 

https://github.com/ScottPlot/ScottPlot/blob/05394f8ab2bafd1816793db6296ade8f9122a383/src/ScottPlot5/ScottPlot5/Plottables/HorizontalLine.cs#L63-L65

https://github.com/ScottPlot/ScottPlot/blob/05394f8ab2bafd1816793db6296ade8f9122a383/src/ScottPlot5/ScottPlot5/Plottables/VerticalLine.cs#L62-L64

Rather than get position from the `rp.DataRect`, the position should look at `rp.Layout` ... probably the `PanelOffsets` dictionary with the panel whose axis matches the `Axis` property in the axis line class whose code you're editing.

**Comment by swharden** [comment] 2024-06-29 10:56
here's a reproducible code sample

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/7f2d5032-a688-4cce-a719-94c72641546c)


```cs
LeftAxis ax1 = (LeftAxis)formsPlot1.Plot.Axes.Left;
LeftAxis ax2 = formsPlot1.Plot.Axes.AddLeftAxis();
LeftAxis ax3 = formsPlot1.Plot.Axes.AddLeftAxis();

var sig1 = formsPlot1.Plot.Add.Signal(Generate.RandomWalk(100, 1));
var sig2 = formsPlot1.Plot.Add.Signal(Generate.RandomWalk(100, 100));
var sig3 = formsPlot1.Plot.Add.Signal(Generate.RandomWalk(100, 10000));

ax1.Color(sig1.Color);
ax2.Color(sig2.Color);
ax3.Color(sig3.Color);

sig1.Axes.YAxis = ax1;
sig2.Axes.YAxis = ax2;
sig3.Axes.YAxis = ax3;

var line1 = formsPlot1.Plot.Add.HorizontalLine(sig1.Data.GetY(50));
var line2 = formsPlot1.Plot.Add.HorizontalLine(sig1.Data.GetY(50));
var line3 = formsPlot1.Plot.Add.HorizontalLine(sig1.Data.GetY(50));

line1.Axes.YAxis = ax1;
line2.Axes.YAxis = ax2;
line3.Axes.YAxis = ax3;

line1.Color = sig1.Color;
line2.Color = sig2.Color;
line3.Color = sig3.Color;

line1.Text = "Axis 1";
line2.Text = "Axis 2";
line3.Text = "Axis 3";
```

**Comment by swharden** [comment] 2024-06-29 10:59
I'm about to commit the change. Afterword it will look like this

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/1e74dd50-662a-45b9-85b2-316b59ef370b)

**Comment by swharden** [comment] 2024-06-29 11:02
Hi @fuxinsen and @mengfanmin123, this was fixed by https://github.com/ScottPlot/ScottPlot/commit/0b7eb3ecc27a3218932ef1b09f5abdfa507908ed

**Closed** 2024-06-29 11:01 UTC
Labels: ⚠️ HIGH PRIORITY, Help Wanted

**Comment by mengfanmin123** [comment] 2024-07-07 04:31
There is no problem when  horizontalLine position label placed on the left additional axis with version 5.0.36, and I also want to set  horizontalLine position label on the  right additional axis，so I made the following modifications in  [ScottPlot/src/ScottPlot5/ScottPlot5/Plottables/HorizontalLine.cs](https://github.com/ScottPlot/ScottPlot/blob/05394f8ab2bafd1816793db6296ade8f9122a383/src/ScottPlot5/ScottPlot5/Plottables/HorizontalLine.cs#L63-L65)

`    float x;
     if (Axes.YAxis is RightAxis)
         x = LabelOppositeAxis
             ? rp.DataRect.Left - LabelStyle.PixelPadding.Left
             : rp.DataRect.Right + LabelStyle.PixelPadding.Right + rp.Layout.PanelOffsets[Axes.YAxis];
     else
         x = LabelOppositeAxis
             ? rp.DataRect.Right + LabelStyle.PixelPadding.Right
             : rp.DataRect.Left - LabelStyle.PixelPadding.Left - rp.Layout.PanelOffsets[Axes.YAxis];`

It seems to be working，But there is a slight deviation in the position


![Snipaste_2024-07-07_12-28-21](https://github.com/ScottPlot/ScottPlot/assets/53968763/b74529e0-6a6e-4e50-9f9d-16e67f687ead)




I want to know how to correct the position，thanks.
