### ISSUE TITLE
Alt+Left Click Zooming Rectangle Not Disappearing

### ISSUE THREAD

**Issue by gobikulandaisamy** [ScottPlot/ScottPlot#3350] opened 2024-02-07 14:53 UTC
**Issue:**
I am running ScottPlot 5.0 Demo.
While Clicking Alt+Left mouse button, Zooming rectangle is appearing. After release left mouse  then that rectangle is not disappearing.

**ScottPlot Version:** ScotPlot 5.0.21

**Operating System:** Windows 11 Pro 22H2

**Processor:**  AMD Ryzen 5 5500U with Radeon Graphics

**Video:**

https://github.com/ScottPlot/ScottPlot/assets/4165489/f0198f1e-5949-494e-82fb-5bcaa7996508

**Comment by swharden** [comment] 2024-11-01 01:14
Wow, it took me a while to get to this issue 😅 

I assume it has since been fixed, especially since we have a fully new user input processor.

I'll close this, but we can re-open it if the issue is present in a current version 👍

**Closed by swharden** 2024-11-01 01:14 UTC
