### ISSUE TITLE
SignalXY: How to use GetNearest with signals on multiple axes?

### ISSUE THREAD

**Issue by feichti92** [ScottPlot/ScottPlot#4033] opened 2024-07-03 07:30 UTC
**Issue:** I'm not sure if it is really a bug, or I'm just doin something wrong. If I add 2 SignalXY signals to my plot, where each signal has it's own vertical axis with a different value range, it makes a difference which signal I add first to the plot. The first signal is binded to the main axis (Plot.Axes.Left), for every other signal I add an axis (Plot.Axes.AddLeftAxis()). I have to add the signal with the highest/maximum value on the vertical axis at first, to make the GetNearest method work. If I add a binary signal (where the max. value is ofc 1) before a signal for e.g. a rotational speed with max. value 2500, I won't find any nearest point of the rotational speed signal. I always search for nearest point with the according axis (see code snippet below).

**ScottPlot Version:** 5.0.34

**Code Sample:**
```cs
foreach (SignalXY sig in signals)
{
  Coordinates mouseLocation = this.pl_Plot.Plot.GetCoordinates(mousePixel, sig.Axes.XAxis, sig.Axes.YAxis);
  DataPoint point = sig.GetNearest(mouseLocation, this.pl_Plot.Plot.LastRender);
  Pixel p_point = this.pl_Plot.Plot.GetPixel(point.Coordinates, sig.Axes.XAxis, sig.Axes.YAxis);
  double distance = p_point.DistanceFrom(mousePixel);
}
```

**Comment by ax-iv** [comment] 2024-07-08 12:36
My observation: `GetNearest` searches for the nearest point without taking into account the scales of the axes. This method works perfectly for axes in which the dimension of the `X` axis is equal to the dimension of the `Y` axis. If the axes are stretched, then the search takes place on an oval. Additionally, if you have several graphs with different axis scales, then the search areas are different. It is necessary to correct this method so that it takes into account the scales of the graphs

**Comment by asd20752** [comment] 2024-11-04 10:26
Did you end up finding a solution to this issue?

**Comment by swharden** [comment] 2024-11-04 14:41
Hi @asd20752 and the group,

A primary reason this issue hasn't had much progress is because the description is a bit complicated, and there's no coded provided to let someone else demonstrate the issue. If some sample code is added to help us recreate the issue, it's much more likely to get picked up and resolved in good time.

Also, an animated GIF showing the problem could go a long way toward communicating what the issue is. I'm struggling a bit to understand it myself after reading the text above a few times. https://www.screentogif.com/

**Comment by feichti92** [comment] 2024-11-05 17:14
Yeah, I understand that my explanation is not that clear. I tried to describe my problem my specific usage. I will create a little application and try to reproduce that issue. Hopefully I find some time the next weeks 😅

**Closed** 2024-11-05 17:23 UTC
