### ISSUE TITLE
DataLogger ViewSlide() does not work as expected when using right axes

### ISSUE THREAD

**Issue by jpgarza93** [ScottPlot/ScottPlot#3637] opened 2024-04-10 14:27 UTC
**Issue:** 
When I add a right Axis to my plot the DataLogger.ViewSlide() stops working as expected.

**ScottPlot Version:**
5.0.25

**Code Sample:** 
To reproduce, I added the last 2 lines in your demo datalogger file
```cs
Logger = formsPlot1.Plot.Add.DataLogger();

var axis = formsPlot1.Plot.Axes.AddRightAxis();
Logger.Axes.YAxis = axis;
```

**Comment by swharden** [comment] 2024-04-11 11:26
Hi @jpgarza93, thanks for reporting this! I think it has been fixed in #3641 and will be working better in the next release (5.0.56). If not, let me know and we can re-open this issue and take a closer look 👍

**Comment by jpgarza93** [comment] 2024-04-15 21:49
It appears to me that using the function `formsPlot1.Plot.Axes.AddRightAxis();` still causes the issue. I have tested in the demo project with the latest version 5.0.26

**Comment by swharden** [comment] 2024-04-15 21:50
Hi @jpgarza93, thanks for following-up! Can you copy/paste the code you used to recreate that issue? Thanks!

**Comment by jpgarza93** [comment] 2024-04-15 21:54
Hello @swharden, It is the same as in the first comment, does that work? Else, I can provide anything needed.

**Comment by swharden** [comment] 2024-04-15 21:56
Thanks for the tip! I'll look into it now 👍 
![3637](https://github.com/ScottPlot/ScottPlot/assets/4165489/7adde1b8-b244-4e17-9fc4-5839dbb195df)

**Comment by swharden** [comment] 2024-04-15 21:59
Actually, do you need to ever call `var axis = formsPlot1.Plot.Axes.AddRightAxis();`?

The demo plots data on the _built-in_ right axis (`formsPlot1.Plot.Axes.Right`) without having to create a new (additional) right axis

You can tell your plotted objects to use the built-in `formsPlot1.Plot.Axes.Right` and you may be set!

**Comment by jpgarza93** [comment] 2024-04-15 22:05
Okay, you tell me. Maybe I can accomplish it differently. But currently I use `Axes.AddRightAxis()` because I allow the users to trace 1-N dataloggers and display it as below image:
![image](https://github.com/ScottPlot/ScottPlot/assets/79015116/c42fcdfa-6b95-4ac5-abe2-227d0f3f070b)

**Comment by swharden** [comment] 2024-04-15 22:06
Ah, gotcha. It sounds like you're using multiple dataloggers. Thanks for the clarification! I'll modify the demo app to test this and follow-up shortly 👍

**Comment by swharden** [comment] 2024-04-15 22:31
![streamermultiple](https://github.com/ScottPlot/ScottPlot/assets/4165489/c5d18cd9-826c-42c7-9fa6-44c08e951f7d)

Hope this helps! I'm leaning on some styling methods that aren't in the main library yet but this should convey the gist. We can open this up again if you hit any snags, but I think this will do it! 🚀 

```cs
using ScottPlot;

namespace WinForms_Demo.Demos;
public partial class DataStreamer : Form, IDemoWindow
{
    public string Title => "Data Streamer";
    public string Description => "Plots live streaming data as a fixed-width line plot, " +
        "shifting old data out as new data comes in.";

    readonly System.Windows.Forms.Timer AddNewDataTimer = new() { Interval = 10, Enabled = true };
    readonly System.Windows.Forms.Timer UpdatePlotTimer = new() { Interval = 50, Enabled = true };

    readonly ScottPlot.Plottables.DataStreamer Streamer1;
    readonly ScottPlot.Plottables.DataStreamer Streamer2;

    readonly ScottPlot.DataGenerators.RandomWalker Data1 = new();
    readonly ScottPlot.DataGenerators.RandomWalker Data2 = new();

    public DataStreamer()
    {
        InitializeComponent();

        // add a streamers to the plot
        Streamer1 = formsPlot1.Plot.Add.DataStreamer(1000);
        Streamer2 = formsPlot1.Plot.Add.DataStreamer(1000);

        // identify the axes to use
        IYAxis yAxisRight1 = formsPlot1.Plot.Axes.Right;
        IYAxis yAxisRight2 = formsPlot1.Plot.Axes.AddRightAxis();

        // set axis colors to match the data streamers they display
        formsPlot1.Plot.Axes.Color(yAxisRight1, Streamer1.Color);
        formsPlot1.Plot.Axes.Color(yAxisRight2, Streamer2.Color);

        // wire streamers to axes
        Streamer1.Axes.YAxis = yAxisRight1;
        Streamer2.Axes.YAxis = yAxisRight2;

        // setup a timer to add data to the streamer periodically
        AddNewDataTimer.Tick += (s, e) =>
        {
            Streamer1.AddRange(Data1.Next(10));
            Streamer2.AddRange(Data2.Next(10));
        };

        // setup a timer to request a render periodically
        UpdatePlotTimer.Tick += (s, e) =>
        {
            if (Streamer1.HasNewData || Streamer2.HasNewData)
            {
                formsPlot1.Refresh();
            }
        };
    }
}
```

**Comment by jpgarza93** [comment] 2024-04-15 22:39
Hello @swharden, are you suggesting I use datastreamer instead of datalogger?

I do use the datalogger functions ViewFull and ViewSlide

**Comment by swharden** [comment] 2024-04-15 22:46
> Hello @swharden, are you suggesting I use datastreamer instead of datalogger?

Oh, sorry 😅 I was addressing another issue today that involved the streamer and I mixed-up the use case

I'm pretty sure the concept will be the same for data loggers... I'll see if I can adapt that demo to test it now

**Comment by swharden** [comment] 2024-04-15 22:47
Tested it with a data logger and it works the same 👍 

```cs
using ScottPlot;

namespace WinForms_Demo.Demos;
public partial class DataStreamer : Form, IDemoWindow
{
    public string Title => "Data Streamer";
    public string Description => "Plots live streaming data as a fixed-width line plot, " +
        "shifting old data out as new data comes in.";

    readonly System.Windows.Forms.Timer AddNewDataTimer = new() { Interval = 10, Enabled = true };
    readonly System.Windows.Forms.Timer UpdatePlotTimer = new() { Interval = 50, Enabled = true };

    readonly ScottPlot.Plottables.DataLogger Logger1;
    readonly ScottPlot.Plottables.DataLogger Logger2;

    readonly ScottPlot.DataGenerators.RandomWalker Data1 = new();
    readonly ScottPlot.DataGenerators.RandomWalker Data2 = new();

    public DataStreamer()
    {
        InitializeComponent();

        // add a streamers to the plot
        Logger1 = formsPlot1.Plot.Add.DataLogger();
        Logger2 = formsPlot1.Plot.Add.DataLogger();

        // identify the axes to use
        IYAxis yAxisRight1 = formsPlot1.Plot.Axes.Right;
        IYAxis yAxisRight2 = formsPlot1.Plot.Axes.AddRightAxis();

        // set axis colors to match the data streamers they display
        formsPlot1.Plot.Axes.Color(yAxisRight1, Logger1.Color);
        formsPlot1.Plot.Axes.Color(yAxisRight2, Logger2.Color);

        // wire streamers to axes
        Logger1.Axes.YAxis = yAxisRight1;
        Logger2.Axes.YAxis = yAxisRight2;

        // setup a timer to add data to the streamer periodically
        AddNewDataTimer.Tick += (s, e) =>
        {
            Logger1.Add(Data1.Next(10));
            Logger2.Add(Data2.Next(10));
        };

        // setup a timer to request a render periodically
        UpdatePlotTimer.Tick += (s, e) =>
        {
            if (Logger1.HasNewData || Logger2.HasNewData)
            {
                formsPlot1.Refresh();
            }
        };
    }
}
```

**Comment by jpgarza93** [comment] 2024-04-15 23:26
So is the issue with `ViewSlide()` and `AddRightAxis()` resolved? 

Sorry, I am a bit confused with the styling comments 😅

**Comment by swharden** [comment] 2024-04-15 23:33
It's okay. I actually do not think there is any issue to resolve. I explicitly called `ViewSlide()` and confirms it works as expected 👍 

```cs
using ScottPlot;

namespace WinForms_Demo.Demos;
public partial class DataStreamer : Form, IDemoWindow
{
    public string Title => "Data Streamer";
    public string Description => "Plots live streaming data as a fixed-width line plot, " +
        "shifting old data out as new data comes in.";

    readonly System.Windows.Forms.Timer AddNewDataTimer = new() { Interval = 10, Enabled = true };
    readonly System.Windows.Forms.Timer UpdatePlotTimer = new() { Interval = 50, Enabled = true };

    readonly ScottPlot.Plottables.DataLogger Logger1;
    readonly ScottPlot.Plottables.DataLogger Logger2;

    readonly ScottPlot.DataGenerators.RandomWalker Data1 = new();
    readonly ScottPlot.DataGenerators.RandomWalker Data2 = new();

    public DataStreamer()
    {
        InitializeComponent();

        // add a streamers to the plot
        Logger1 = formsPlot1.Plot.Add.DataLogger();
        Logger2 = formsPlot1.Plot.Add.DataLogger();

        // enable slide view
        Logger1.ViewSlide();
        Logger2.ViewSlide();

        // identify the axes to use
        IYAxis yAxisRight1 = formsPlot1.Plot.Axes.Right;
        IYAxis yAxisRight2 = formsPlot1.Plot.Axes.AddRightAxis();

        // set axis colors to match the data streamers they display
        formsPlot1.Plot.Axes.Color(yAxisRight1, Logger1.Color);
        formsPlot1.Plot.Axes.Color(yAxisRight2, Logger2.Color);

        // wire streamers to axes
        Logger1.Axes.YAxis = yAxisRight1;
        Logger2.Axes.YAxis = yAxisRight2;

        // setup a timer to add data to the streamer periodically
        AddNewDataTimer.Tick += (s, e) =>
        {
            Logger1.Add(Data1.Next(10));
            Logger2.Add(Data2.Next(10));
        };

        // setup a timer to request a render periodically
        UpdatePlotTimer.Tick += (s, e) =>
        {
            if (Logger1.HasNewData || Logger2.HasNewData)
            {
                formsPlot1.Refresh();
            }
        };
    }
}
```

**Comment by jpgarza93** [comment] 2024-04-16 14:23
I am still seeing the issue, I can see sometimes some configuration makes it work, but if I just run this code and click slide I can see the issue :(
```cs
namespace WinForms_Demo.Demos;

public partial class DataLogger : Form, IDemoWindow
{
    public string Title => "Data Logger";
    public string Description => "Plots live streaming data as a growing line plot.";

    readonly System.Windows.Forms.Timer AddNewDataTimer = new() { Interval = 10, Enabled = true };
    readonly System.Windows.Forms.Timer UpdatePlotTimer = new() { Interval = 50, Enabled = true };

    readonly ScottPlot.Plottables.DataLogger Logger;

    public DataLogger()
    {
        InitializeComponent();

        Logger = formsPlot1.Plot.Add.DataLogger();

        var axis = formsPlot1.Plot.Axes.AddRightAxis();
        Logger.Axes.YAxis = axis;

        // disable mouse interaction by default
        formsPlot1.Interaction.Disable();

        // setup a timer to add data to the streamer periodically
        AddNewDataTimer.Tick += (s, e) =>
        {
            var newValues = ScottPlot.Generate.RandomWalker.Next(10);
            Logger.Add(newValues);
        };

        // setup a timer to request a render periodically
        UpdatePlotTimer.Tick += (s, e) =>
        {
            if (Logger.HasNewData)
            {
                formsPlot1.Plot.Title($"Processed {Logger.Data.CountTotal:N0} points");
                formsPlot1.Refresh();
            }
        };

        // setup configuration actions
        btnFull.Click += (s, e) => Logger.ViewFull();
        btnJump.Click += (s, e) => Logger.ViewJump();
        btnSlide.Click += (s, e) => Logger.ViewSlide();

        // control automatic axis limit modification behavior
        chkManageLimits.CheckedChanged += (s, e) =>
        {
            if (chkManageLimits.Checked)
            {
                Logger.ManageAxisLimits = true;
                formsPlot1.Interaction.Disable();
                formsPlot1.Plot.Axes.AutoScale();
            }
            else
            {
                Logger.ManageAxisLimits = false;
                formsPlot1.Interaction.Enable();
            }
        };

        // switch between using primary and secondary Y axes
        chkRightAxis.CheckedChanged += (s, e) =>
        {
            lock (formsPlot1.Plot.Sync)
            {
                // reset old axis limits so ticks are not displayed on unused axes 
                formsPlot1.Plot.Axes.Left.Range.Reset();
                formsPlot1.Plot.Axes.Right.Range.Reset();

                // tell the datalogger which axis to use and modify moving forward
                Logger.Axes.YAxis = chkRightAxis.Checked
                    ? formsPlot1.Plot.Axes.Right
                    : formsPlot1.Plot.Axes.Left;
            }
        };
    }
}
```
![scottplot-5-datalogger-slide-issue](https://github.com/ScottPlot/ScottPlot/assets/79015116/c36884c0-5676-4e58-8880-09f9938db370)

**Comment by swharden** [comment] 2024-04-17 22:47
Hi @jpgarza93, you you achieve the expected behavior if you replace:
```cs
var axis = formsPlot1.Plot.Axes.AddRightAxis();
Logger.Axes.YAxis = axis;
```

with this:
```cs
var axis = formsPlot1.Plot.Axes.Right;
Logger.Axes.YAxis = axis;
```

**Comment by swharden** [comment] 2024-04-17 22:49
I think the misunderstanding is coming from the fact that the plot starts up with 4 axes ready to go (left, right, bottom, top), and adding _more_ axes is an advanced feature for users who want multiple axes on one side, like https://scottplot.net/cookbook/5.0/MultiAxis/MultiAxisQuickstart/

**Comment by jpgarza93** [comment] 2024-04-18 14:41
Hello @swharden

Yes, I am trying to use Multiple right axes. I still see the issue, the issue appears to go away when a left axis exists. I only use right axes. 

I tweaked the datalogger demo code to use 2 dataloggers. Notice how it does not work when I have my 2 right axes, but as soon as I toggle the right axis (making one of them left) it works.

```cs
using NUnit.Framework.Internal;

namespace WinForms_Demo.Demos;

public partial class DataLogger : Form, IDemoWindow
{
    public string Title => "Data Logger";
    public string Description => "Plots live streaming data as a growing line plot.";

    readonly System.Windows.Forms.Timer AddNewDataTimer = new() { Interval = 10, Enabled = true };
    readonly System.Windows.Forms.Timer UpdatePlotTimer = new() { Interval = 50, Enabled = true };

    readonly ScottPlot.Plottables.DataLogger Logger1;
    readonly ScottPlot.Plottables.DataLogger Logger2;

    public DataLogger()
    {
        InitializeComponent();

        Logger1 = formsPlot1.Plot.Add.DataLogger();
        Logger2 = formsPlot1.Plot.Add.DataLogger();

        var axis1 = formsPlot1.Plot.Axes.Right;
        Logger1.Axes.YAxis = axis1;

        var axis2 = formsPlot1.Plot.Axes.AddRightAxis();
        Logger2.Axes.YAxis = axis2;

        // disable mouse interaction by default
        formsPlot1.Interaction.Disable();

        // setup a timer to add data to the streamer periodically
        AddNewDataTimer.Tick += (s, e) =>
        {
            var newValues = ScottPlot.Generate.RandomWalker.Next(10);
            Logger1.Add(newValues);
            Logger2.Add(newValues.Select(x => x * 4));
        };

        // setup a timer to request a render periodically
        UpdatePlotTimer.Tick += (s, e) =>
        {
            if (Logger1.HasNewData || Logger2.HasNewData)
            {
                formsPlot1.Plot.Title($"Logger1: {Logger1.Data.CountTotal:N0} points - Logger2: {Logger2.Data.CountTotal:N0} points");
                formsPlot1.Refresh();
            }
        };

        // setup configuration actions
        btnFull.Click += (s, e) => { Logger1.ViewFull(); Logger2.ViewFull(); };
        btnJump.Click += (s, e) => { Logger1.ViewJump(); Logger2.ViewJump(); };
        btnSlide.Click += (s, e) => { Logger1.ViewSlide(); Logger2.ViewSlide(); };

        // control automatic axis limit modification behavior
        chkManageLimits.CheckedChanged += (s, e) =>
        {
            if (chkManageLimits.Checked)
            {
                Logger1.ManageAxisLimits = true;
                Logger2.ManageAxisLimits = true;
                formsPlot1.Interaction.Disable();
                formsPlot1.Plot.Axes.AutoScale();
            }
            else
            {
                Logger1.ManageAxisLimits = false;
                Logger2.ManageAxisLimits = false;
                formsPlot1.Interaction.Enable();
            }
        };

        // switch between using primary and secondary Y axes
        chkRightAxis.Checked = true;
        chkRightAxis.CheckedChanged += (s, e) =>
        {
            lock (formsPlot1.Plot.Sync)
            {
                // reset old axis limits so ticks are not displayed on unused axes 
                formsPlot1.Plot.Axes.Left.Range.Reset();

                // tell the datalogger which axis to use and modify moving forward
                Logger1.Axes.YAxis = chkRightAxis.Checked
                    ? formsPlot1.Plot.Axes.Right
                    : formsPlot1.Plot.Axes.Left;
            }
        };
    }
}
```
 
![datalogger-2axes-broken](https://github.com/ScottPlot/ScottPlot/assets/79015116/e7e27f1d-b855-437e-9e0f-32393b0058a3)

**Comment by swharden** [comment] 2024-04-21 17:43
Thanks for following-up @jpgarza93! I created a simpler demo that reproduces the core issue. As soon as the plot is resized, the plottable tries to adjust axis limits, and the left axis appears again

```cs
    public DataLogger()
    {
        InitializeComponent();

        formsPlot1.Interaction.Disable();

        var logger = formsPlot1.Plot.Add.DataLogger();
        logger.Axes.YAxis = formsPlot1.Plot.Axes.Right;
        logger.Add(ScottPlot.Generate.RandomWalk(100));
    }
```

![appear](https://github.com/ScottPlot/ScottPlot/assets/4165489/4b8da0c6-3430-48c9-9927-722f7ba54d4b)

**Comment by swharden** [comment] 2024-04-21 17:45
Here's an even simpler reproducible example. It confirms the issue is not related to the datalogger.

```cs
public DataLogger()
{
    InitializeComponent();

    var sig = formsPlot1.Plot.Add.Signal(Generate.Sin());
    sig.Axes.YAxis = formsPlot1.Plot.Axes.Right;
}
```

**Comment by swharden** [comment] 2024-04-21 21:15
Got it! Thanks for your persistence @jpgarza93. This should be fixed in the next release 🚀 https://github.com/ScottPlot/ScottPlot/commit/d0796fa13be2779267d75ad055a50640aa3bab43

**Closed** 2024-04-21 21:15 UTC
Labels: ⚠️ HIGH PRIORITY

**Comment by jpgarza93** [comment] 2024-04-22 13:01
@swharden thank you for your dedication, time, and tireless efforts!
