### ISSUE TITLE
NuGet error when installing ScottPlot 5.0.3-beta

### ISSUE THREAD

**Issue by cvdevol** [ScottPlot/ScottPlot#2558] opened 2023-04-03 23:38 UTC
The OpenTK packages won't install to a Wpf project with .NET 4.8
```
Error 
Could not install package 'OpenTK.Compute 5.0.0-pre.8'. 
You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', 
but the package does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author.
```

**Comment by swharden** [comment] 2023-04-03 23:57
Thanks for reporting this @cvdevol! I'll issue a fix tonight 👍

**Comment by swharden** [comment] 2023-04-04 00:00
I think the issue is here

https://github.com/ScottPlot/ScottPlot/blob/1369ffd7d5c9fd325d85c190f13d788af7e12f89/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WPF/ScottPlot.WPF.csproj#L39-L46

The conditional package logic shouldn't be so specific to the .NET version

* Related: #2399

**Comment by swharden** [comment] 2023-04-04 00:14
@cvdevol I created a new .NET 4.8 project with Visual Studio, added the latest ScottPlot 5 preview package on NuGet, and it worked well in my hands.

```xml
<Window x:Class="WpfApp8.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp8" 
        xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <ScottPlot:WpfPlot Name="WpfPlot1" />
</Window>
```

I think the problem is that you may have "upgraded" some of the dependent packages which is what caused the version conflicts. I'm confident enough this is the cause of this issue that I'll close it, but feel free to re-open it if you continue to have trouble 👍

**Closed by swharden** 2023-04-04 00:14 UTC
Labels: ⚠️ HIGH PRIORITY, BUG

**Comment by cvdevol** [comment] 2023-04-05 03:38
Yes, I did in fact do an update after installing. Everything updated fine except the OpenTK packages. But ScottPlot works fine without them.
