### ISSUE TITLE
ScottPlot5: WPF sandbox throws exception due to OpenTK version

### ISSUE THREAD

**Issue by KroMignon** [ScottPlot/ScottPlot#2563] opened 2023-04-04 12:31 UTC
## Bug Report

**Issue:** 

I tried to build ScottPlot5 for WPF and then run the sandbox application, but run into multiple errors.

**Reproducing:**

First I had to add `ScottPlot.OpenGL.csproj` in to Solution filter `ScottPlot5-wpf.slnf`.
Now I can build the sandbox application, but I've got following failure
![image](https://user-images.githubusercontent.com/3978902/229789825-31eefd6d-a826-4f36-b496-49830aa5efdb.png)

It seems to be a failure with OpenTK, but I cannot figure out how to solve it.
The Sandbox application is .NET6 based, but ScottPlot5.WPF uses .NET 4.6.2, maybe this is the main issue.

I am not OpenGL expert and don't have any experience with OpenTK, I am lost 🕳️ 

### System Details
* **ScottPlot Version:** 5.2
* **Operating System:** Windows 10
* **Application Type:** WPF

**Comment by swharden** [comment] 2023-04-04 16:20
Hi @KroMignon, thanks for reporting this!

This error affecting the WPF control was caused by recent efforts to share OpenGL-enabled plot types across the WinForms and WPF controls (#2399, #2496), but unfortunately they require different versions of OpenTK resulting in exceptions like the one you show.

I think the way to fix this is to convert the `ScottPlot.OpenGL.csproj` project into a shared source project `ScottPlot.OpenGL.csproj` and hope both controls can compile the same source code even with different OpenTK versions 🤞 

I think I can solve this issue tonight, but I recognize this makes it hard to work on the WPF control in the mean time 😅

**Comment by KroMignon** [comment] 2023-04-04 21:20
> I think I can solve this issue tonight, but I recognize this makes it hard to work on the WPF control in the mean time 😅

I hope you can find a way to solve this. I had looked quickly OpenTK project. It seems that OpenTK 4.x already had a WPF support. This could simplify Plot control creation 🤓... or not 😞

**Comment by swharden** [comment] 2023-04-04 23:39
Good news is that this is only a problem with the sandbox app (not the control itself)

I got it fixed in #2536 but refactoring the `ScottPlot.OpenGL` project to allow some type of _OpenGL service injection_ may be a solution to this ongoing problem

**Closed** 2023-04-05 00:03 UTC
Labels: ⚠️ HIGH PRIORITY, BUG
