### ISSUE TITLE
ScottPlot performance regarding plotting polygons.

### ISSUE THREAD

**Issue by VacaruAlex** [ScottPlot/ScottPlot#3476] opened 2024-03-15 12:25 UTC
**Question:** (Hi,  am developing a tool which extracts data from a microcontroller, I want to plot the as polygons, the data represents the timestamps between each event took place. The idea is that the data set is large and I have problems when using  ZoomIn, ZoomOut, DragPan these ecents are very laggy, as an idea just 1 Fps.)

**ScottPlot Version:** ScottPlot 5.0.21

```cs
CustomActions.ToggleBenchmark = (IPlotControl control) =>
{
    control.Plot.Benchmark.IsVisible = !control.Plot.Benchmark.IsVisible;
    control.Refresh();
};


CustomActions.ZoomIn = (IPlotControl control, Pixel pixel, LockedAxes locked) =>
{
  
    double num = 1.15;
    double fracX = (locked.X ? 1.0 : num);
    double fracY = (locked.Y ? 1.0 : num);
    control.Plot.MouseZoom(fracX, fracY, pixel);
    /* Get the limits of the plot */
    AxisLimits limits = control.Plot.Axes.GetLimits();
    /* Get the minimum value of the X axis */
    CoordinateRange rangeX = limits.XRange;
    int minX = (int)rangeX.Min;
    int maxX = (int)rangeX.Max;
    int tick_step_X = (maxX - minX) / 10;
    /* Generate the ticks for the X axis */
    //Console.WriteLine(tick_step_X);
    myTickGenerator.Interval = tick_step_X;
    control.Plot.Axes.Bottom.TickGenerator = myTickGenerator;
    control.Refresh();
    control.Plot.Render();
};

CustomActions.ZoomOut = (IPlotControl control, Pixel pixel, LockedAxes locked) =>
{
    
    double num = 0.85;
    double fracX = (locked.X ? 1.0 : num);
    double fracY = (locked.Y ? 1.0 : num);
    control.Plot.MouseZoom(fracX, fracY, pixel);
    /* Get the limits of the plot */
    AxisLimits limits = control.Plot.Axes.GetLimits();
    /* Get the minimum value of the X axis */
    CoordinateRange rangeX = limits.XRange;
    //int tick_step_X = (int)rangeX.Span / 10;
    int minX = (int)rangeX.Min;
    int maxX = (int)rangeX.Max;
    int tick_step_X = (maxX - minX)/10;
    //Console.WriteLine(tick_step_X);
    /* Generate the ticks for the X axis */
    myTickGenerator.Interval = tick_step_X;
    control.Plot.Axes.Bottom.TickGenerator = myTickGenerator;
    control.Refresh();
};

CustomActions.DragPan = (IPlotControl control, MouseDrag drag, LockedAxes locked) =>
{
    Pixel mouseNow = new(locked.X ? drag.From.X : drag.To.X, locked.Y ? drag.From.Y : drag.To.Y);
    control.Plot.MousePan(drag.InitialLimits, drag.From, mouseNow);
    control.Refresh();
};

 public void InsertRectangle(int current_index,List<INFO> infoList, double key, FormsPlot form, ScottPlot.Color FillColor, ScottPlot.Color LineColor, float width)
 {

     double x1 = infoList[current_index].timestamp;
     // Second point on X - axis
     double x2 = infoList[current_index + 1].timestamp;
     // Second point on Y - axis because the plot will be on the negative side for Y
     double y1 = key - 0.3;
     // First point on Y - axis because the plot will be on the negative side for Y
     double y2 = key + 0.3;

     /* Add polygon with scottplot */
     var rp = form.Plot.Add.Rectangle(x1, x2, -y2, -y1);
     rp.FillStyle.Color = FillColor;
     rp.LineStyle.Color = LineColor;
     rp.LineStyle.Width = width;
 }
```

How can I improve the performance, I tried plotting markers for each element and I get the same problem, is this a CPU problem or a Gpu is needed ?

**Comment by swharden** [comment] 2024-03-16 23:44
Hi @VacaruAlex, thanks for this question! Unfortunately the code sample you provided is incomplete so I can't test it out on my machine. 

How many polygons are you trying to display? The system is definitely expected to slow down if that number gets extremely large.

You may achieve superior performance of you are able to display your data as values on a heatmap! I find heatmaps maintain high performance even with millions of cell values. https://scottplot.net/cookbook/5.0/Heatmap/

I'll close this issue now because it's not particularly actionable without a reproducible code example, but I'm happy to re-open it if we make progress into understanding the problem 👍

**Closed by swharden** 2024-03-16 23:44 UTC
