### ISSUE TITLE
SP5: WPFplot not working after WindowClosingEvent

### ISSUE THREAD

**Issue by minjjKang** [ScottPlot/ScottPlot#2700] opened 2023-06-29 07:40 UTC
## Bug Report

**Issue:** 
    In ScottPlot5, WPFplot not working after WindowClosingEvent

**Reproducing:**
    1. window close
    2. close event cancel
    3. wpf plot can't rendering

I think... before my WindowsClosingEvent is run (before closing event cancel),
**/ScottPlot.WPF/SKGLElement.cs/SKGLElementWindowListener** running a window closing event. (it dispose the renderer element)

it need to use the window **closed** event or do something else.

thanks.

### System Details
* **ScottPlot Version:** 5.0.4beta
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET6.0

**Comment by swharden** [comment] 2023-07-05 12:06
Hi @minjjKang, thanks for reporting this

Reviewing the code, it looks like the SKGLElement permanently disposes a lot of things when it is disposed:
https://github.com/ScottPlot/ScottPlot/blob/b7f566d5d2087fa1e5f7b61a45cb021250f32f57/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WPF/SKGLElement.cs#L239-L264

I confirmed that clicking the "X" to close the WPF window causes the SKGLElement to get disposed.

Your question is more of a WPF question than a ScottPlot question: "How do I prevent objects stored as properties in a WPF control from being disposed when the window close is initiated?"

I'm not sure the answer to this, but if you figure it out please share it here so others may find it too!

I'll close this issue since I don't think it represents a problem with ScottPlot

Also, here's the code I used to test this idea:

```cs
using System.ComponentModel;
using System.Windows;

namespace Sandbox.WPF;

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        WpfPlot.Plot.Add.Signal(ScottPlot.Generate.Sin());
        WpfPlot.Plot.Add.Signal(ScottPlot.Generate.Cos());

        this.Closing += MainWindow_Closing;
    }

    private void MainWindow_Closing(object? sender, CancelEventArgs e)
    {
        e.Cancel = true;
    }
}
```

**Closed by swharden** 2023-07-05 12:06 UTC
Labels: BUG

**Comment by minjjKang** [comment] 2023-07-05 12:45
Hi.

What I meant by "not working" is that it is impossible to refresh the plot including interaction.
sorry for i didn't write details.

I wrote the same code as you shared and ran two applications, Scottplot4 and Scottplot5.
```C#
// Scottplot 5
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        plot.Plot.Add.Signal(ScottPlot.Generate.Sin());
        plot.Plot.Add.Signal(ScottPlot.Generate.Cos());

        this.Closing += MainWindow_ClosingEvent;
    }

    private void MainWindow_ClosingEvent(object? sender, CancelEventArgs e)
    {
        e.Cancel = true;
    }
}
```

```C#
// Scottplot 4
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        double[] dataX = new double[] { 1, 2, 3, 4, 5 };
        double[] dataY = new double[] { 1, 4, 9, 16, 25 };

        plot.Plot.AddScatter(dataX, dataY);
        plot.Refresh();

        this.Closing += MainWindow_ClosingEvent;
    }
    private void MainWindow_ClosingEvent(object? sender, CancelEventArgs e)
    {
        e.Cancel = true;
    }
}
```

and, There is a video of the problem below:
    https://youtube.com/shorts/GhnFCOVjh8c?feature=share

Interaction and refresh are works well.
after, Press X to proceed with window closing and cancel the event,
It works fine on Scottplot4, Not in Scottplot5.

**Comment by swharden** [comment] 2023-07-05 22:26
> What I meant by "not working" is that it is impossible to refresh the plot including interaction.
sorry for i didn't write details.

> I wrote the same code as you shared and ran two applications, Scottplot4 and Scottplot5.
> It works fine on Scottplot4, Not in Scottplot5.

I think this is because ScottPlot 5 uses SkiaSharp and the SKGLElement control (which is what is breaking) and ScottPlot 4 does not use that control.

The problem is that closing the WPF calls the SKGLElement's `dispose()` method, and setting `e.Cancel = true` doesn't prevent this disposal. If you can figure out how to prevent WPF from disposing of class objects when the X is clicked, this problem will be solved! 

I think this is a WPF question (not a ScottPlot question), so I'll look into it a little more but I probably won't take too much time away from other issues using my time to figure this one out. If you figure this out though, let me know what you find! Someone in the future may be able to benefit from this solution once it is found 👍

**Comment by swharden** [comment] 2023-07-05 22:31
Figured it out! Let me know if this doesn't work 😉 

```cs
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        WpfPlot.Plot.Add.Signal(ScottPlot.Generate.Sin());
        WpfPlot.Plot.Add.Signal(ScottPlot.Generate.Cos());
        WpfPlot.Refresh();
    }

    protected override void OnClosing(CancelEventArgs e)
    {
        System.Diagnostics.Debug.WriteLine("closing wpf");
        e.Cancel = true;    
    }
}
```
