### ISSUE TITLE
Draggable line on DateTime axis has unexpected snapping behavior

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3809] opened 2024-05-08 10:07 UTC
The Draggable vertical line is not moving with in a second record when DateTime have multiple millisecond records with in a second. It directly moving to next second record.

For example

```
05-08-2024 15:36:10.100
05-08-2024 15:36:10.300
05-08-2024 15:36:10.500
05-08-2024 15:36:10.800
05-08-2024 15:36:11.100
```

Here, while dragging the vertical line, it is moving from `05-08-2024 15:36:10.100` directly to `05-08-2024 15:36:11.100` record. In between records are skipping,

i used the following code:

```cs
private void FormsPlot1_MouseMove(object? sender, MouseEventArgs e)
    {
        // this rectangle is the area around the mouse in coordinate units
        CoordinateRect rect = formsPlot1.Plot.GetCoordinateRect(e.X, e.Y, radius: 10);

        if (PlottableBeingDragged is null)
        {
            // set cursor based on what's beneath the plottable
            var lineUnderMouse = GetLineUnderMouse(e.X, e.Y);
            if (lineUnderMouse is null) Cursor = Cursors.Default;
            else if (lineUnderMouse.IsDraggable && lineUnderMouse is VerticalLine) Cursor = Cursors.SizeWE;
            else if (lineUnderMouse.IsDraggable && lineUnderMouse is HorizontalLine) Cursor = Cursors.SizeNS;
        }
        else
        {
            // update the position of the plottable being dragged
            if (PlottableBeingDragged is HorizontalLine hl)
            {
                hl.Y = rect.VerticalCenter;
                hl.Text = $"{hl.Y:0.00}";
            }
            else if (PlottableBeingDragged is VerticalLine vl)
            {
                vl.X = rect.HorizontalCenter;
                vl.Text = $"{vl.X:0.00}";
            }
            formsPlot1.Refresh();
        }
    }

```

I have a list array of DateTime values with millisecond precision and i want to find the index of the closest DateTime value to the position of the dragged vertical line

**Comment by swharden** [comment] 2024-05-08 16:21
Hi @kareem469, does this problem happen even if you zoom in more? I'm wondering if your current zoom is such that a pixel is one second wide or something, so it would not be possible to drag by smaller than a second

**Comment by kareem469** [comment] 2024-05-08 18:24
Hi @swharden,

For 1 second there will be maximum of 10 records and minimum of 1 record.
For example if 4 records exists between 2 seconds then I want to drag the vertical line and get the exact record while moving verticale line between to secs data

**Comment by swharden** [comment] 2024-06-07 01:20
Hi @kareem469, 

It took a very long time to get to this because your code is incomplete. I started to write an app that can demonstrate the issue you describe, but the code you shared doesn't even contain your snapping code.

I'll close this issue since there isn't enough information here to recreate your original problem, but feel free to open it again if you are able to share a full page of code I can copy/paste into my app and press F5 to reproduce the issue.

See https://scottplot.net/demo/#show-value-under-mouse to find code that relates to snapping near points.

For reference, here's the code I wrote that (like the original post) contains no snapping logic, but may help someone if they decide to pick up this topic in the future.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/77b403f4-507e-4036-8bd6-9b71af8a9e60)

```cs
using ScottPlot;
using ScottPlot.Plottables;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    readonly AxisLine? PlottableBeingDragged = null;

    public Form1()
    {
        InitializeComponent();

        DateTime[] dts = Generate.ConsecutiveDateTimes(100, DateTime.Now, TimeSpan.FromMilliseconds(100));
        double[] values = Generate.RandomWalk(dts.Length);
        formsPlot1.Plot.Add.Scatter(dts, values);
        formsPlot1.Plot.Axes.DateTimeTicksBottom();

        PlottableBeingDragged = formsPlot1.Plot.Add.VerticalLine(0);

        formsPlot1.MouseMove += FormsPlot1_MouseMove;
    }

    private AxisLine? GetLineUnderMouse(float x, float y)
    {
        CoordinateRect rect = formsPlot1.Plot.GetCoordinateRect(x, y, radius: 10);

        foreach (AxisLine axLine in formsPlot1.Plot.GetPlottables<AxisLine>().Reverse())
        {
            if (axLine.IsUnderMouse(rect))
                return axLine;
        }

        return null;
    }

    private void FormsPlot1_MouseMove(object? sender, MouseEventArgs e)
    {
        // this rectangle is the area around the mouse in coordinate units
        CoordinateRect rect = formsPlot1.Plot.GetCoordinateRect(e.X, e.Y, radius: 10);

        if (PlottableBeingDragged is null)
        {
            // set cursor based on what's beneath the plottable
            var lineUnderMouse = GetLineUnderMouse(e.X, e.Y);
            if (lineUnderMouse is null) Cursor = Cursors.Default;
            else if (lineUnderMouse.IsDraggable && lineUnderMouse is VerticalLine) Cursor = Cursors.SizeWE;
            else if (lineUnderMouse.IsDraggable && lineUnderMouse is HorizontalLine) Cursor = Cursors.SizeNS;
        }
        else
        {
            // update the position of the plottable being dragged
            if (PlottableBeingDragged is HorizontalLine hl)
            {
                hl.Y = rect.VerticalCenter;
                hl.Text = $"{hl.Y:0.00}";
            }
            else if (PlottableBeingDragged is VerticalLine vl)
            {
                vl.X = rect.HorizontalCenter;
                vl.Text = $"{vl.X:0.00}";
            }
            formsPlot1.Refresh();
        }
    }
}
```

**Closed** 2024-06-07 01:21 UTC
Labels: Incomplete
