### ISSUE TITLE
Rendering: The recent switch to ClearType displays text poorly on some systems

### ISSUE THREAD

**Issue by r84r** [ScottPlot/ScottPlot#1553] opened 2022-01-13 16:41 UTC
## Bug Report

**Issue:**
After updating from 4.1.27 to 4.1.29, the text/font for the ticks and axis label looks distorted/not clear, like shown in the picture.
![scottplot-ticks](https://user-images.githubusercontent.com/34740220/149370425-206d8558-edd0-4756-be5d-f3bfcc874a33.png)

**Reproducing:**
Can't say how to reproduce. I have used version 4.1.27 before and had no problems. I did not change anything in the whole system or my code. Just updated.

### System Details
* **ScottPlot Version:** 4.1.29
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** NET Framework 4.8

**Comment by swharden** [comment] 2022-01-13 21:46
Hi @r84r, thanks for sharing this! This seems very similar to #1550 and was caused by the recent switch to ClearType #1528 which improved text rendering on _some_ systems but I'm beginning to appreciate not _all_ systems.

Unfortunately I think I need to roll-back using ClearType by default, but hopefully can figure-out a way to make it an option.

@Elgot (#823) if you have any insight about what's causing this, let me know! I suspect it may affect rendering on transparent surfaces and/or non-English default fonts.

**Comment by Elgot** [comment] 2022-01-13 22:00
> Hi @r84r, thanks for sharing this! This seems very similar to #1550 and was caused by the recent switch to ClearType #1528 which improved text rendering on _some_ systems but I'm beginning to appreciate not _all_ systems.
> 
> Unfortunately I think I need to roll-back using ClearType by default, but hopefully can figure-out a way to make it an option.
> 
> @Elgot (#823) if you have any insight about what's causing this, let me know! I suspect it may affect rendering on transparent surfaces and/or non-English default fonts.

I'm not sure, but I would guess that the transparency is the problem. Perhaps the old method can be used in those cases?

**Comment by EFeru** [comment] 2022-01-14 05:49
Hi @swharden if you intend to roll back, personally i prefer to have the rendering as an option. Because on winforms with 4.1.29 the text looks so much better and clear, while with 4.1.27 the text looks foggy. 

Indeed I did lost the transparency similar to #1550 which I fixed by setting the background color to the desired one. However, overall i like much more the clear text, it's much better for the eyes 👀.

**Comment by swharden** [comment] 2022-01-15 05:20
Clarifying the problem, ClearType is always superior _except_ when drawn on top of a transparent background. I can probably add some logic to selectively disable ClearType if the figure background is transparent...

&nbsp; | Transparent Background | Solid Background
---|---|---
**AntiAlias** | ![Test_ClearType_Transparency_AntiAlias-Transparent](https://user-images.githubusercontent.com/4165489/149610071-589d2b55-f957-4a12-9838-51626dd49f72.png) | ![Test_ClearType_Transparency_AntiAlias-OnGray](https://user-images.githubusercontent.com/4165489/149610077-4c236cd1-8924-45aa-ad16-ce42d7bba03b.png)
**ClearType** | ![Test_ClearType_Transparency_ClearType-Transparent](https://user-images.githubusercontent.com/4165489/149610050-873548e4-53fa-4564-a313-6a6c871a9645.png) | ![Test_ClearType_Transparency_ClearType-OnGray](https://user-images.githubusercontent.com/4165489/149610062-fa68dc14-6a19-4017-9a80-d29ff86f6aac.png)

**Comment by swharden** [comment] 2022-01-15 05:58
After thinking about this some more, I realized that an extremely common use-case for ScottPlot is rendering transparent PNGs, in which case ClearType rendering would look poor.

In #1554 I reverted the default rendering behavior to AntiAlias (not ClearType), reverted the WinForms control background back to Transparent, and exposed a method the user can call to specifically enable ClearType:

```cs
ScottPlot.GDI.Drawing.ClearType(true);
```

I know it's hidden deep in the API and unlikely to be easily discovered, and I'd love to leave this on by default, but not working on transparent backgrounds is a deal breaker. I'm confident the transition from `System.Drawing` to `Maui.Graphics` will solve this issue soon! #1036

**Closed** 2022-01-15 06:24 UTC
Labels: BUG

**Comment by swharden** [comment] 2022-01-17 16:01
# Future Users: To improve text rendering with ClearType

```cs
// Enable TrueType
ScottPlot.Drawing.GDI.ClearType(true);

// The default transparent figure background must be replaced with a solid color
formsPlot1.Plot.Style(figureBackground: System.Drawing.SystemColors.Control);
```

TrueType Off & Transparent Background (default) | TrueType On & Transparent Background | TrueType On & Solid Background
---|---|---
![image](https://user-images.githubusercontent.com/4165489/149802373-5e8985f3-be46-42c5-bb6d-fb12bc5e6ce8.png)|![image](https://user-images.githubusercontent.com/4165489/149802411-290ed68b-f89b-48ec-9181-1038c7c27c29.png)|![image](https://user-images.githubusercontent.com/4165489/149802448-c695ea75-5b12-49f7-8f9c-3a7ee9b193b9.png)

**Comment by r84r** [comment] 2022-01-20 05:18
Thx for sharing and solving. The transparant background was the issue.
