### ISSUE TITLE
How to print a single data live?

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#764] opened 2021-02-09 07:36 UTC
Hello, 

There is a refreshing data every 100 ms. I want to show this data on the graph but I was not successful. I can't see any data on the chart when I write it as below. I would be happy if you could help.

`System.Drawing.Color color = System.Drawing.Color.FromArgb(255, 139, 26, 26);`
`double[] angle1Array = new double[1];`
```
private void DispactherTimer_Tick(object sender, EventArgs e)
        {
            try
            {
                    angle1Array[0] = Convert.ToDouble(angle1.Text);
                    dateTime = dateTime.AddMilliseconds(100);
                    Angle_Angle1_Graphic.plt.PlotSignal(angle1Array, 864000, xOffset: dateTime.ToOADate(), color: color, markerSize: 5);
                    Angle_Angle1_Graphic.plt.AxisAuto();
                    Angle_Angle1_Graphic.Render();
            }
            catch
            {

            }
        }
```

I tested the growing data in the demo in my own application, I am having a similar problem. Could there be a situation about the version difference?

Version 4.0.48

Growing Data Code

```
    public partial class MainWindow : Window
    {
        public double[] data = new double[100_000];
        int nextDataIndex = 1;

        PlottableSignal signalPlot;
        Random rand = new Random(0);

        private DispatcherTimer _updateDataTimer;
        private DispatcherTimer _renderTimer;

        public MainWindow()
        {
            InitializeComponent();

            var signalPlot = wpfPlot1.plt.PlotSignal(data);
            wpfPlot1.plt.YLabel("Value");
            wpfPlot1.plt.XLabel("Sample Number");

            _updateDataTimer = new DispatcherTimer();
            _updateDataTimer.Interval = TimeSpan.FromMilliseconds(1);
            _updateDataTimer.Tick += UpdateData;
            _updateDataTimer.Start();

            _renderTimer = new DispatcherTimer();
            _renderTimer.Interval = TimeSpan.FromMilliseconds(20);
            _renderTimer.Tick += Render;
            _renderTimer.Start();

            Closed += (sender, args) =>
            {
                _updateDataTimer?.Stop();
                _renderTimer?.Stop();
            };
        }


        void UpdateData(object sender, EventArgs e)
        {
            if (nextDataIndex >= data.Length)
            {
                throw new OverflowException("data array isn't long enough to accomodate new data");
                // in this situation the solution would be:
                //   1. clear the plot
                //   2. create a new larger array
                //   3. copy the old data into the start of the larger array
                //   4. plot the new (larger) array
                //   5. continue to update the new array
            }

            double randomValue = Math.Round(rand.NextDouble() - .5, 3);
            double latestValue = data[nextDataIndex - 1] + randomValue;
            data[nextDataIndex] = latestValue;
            ReadingsTextbox.Text = $"{nextDataIndex + 1}";
            LatestValueTextbox.Text = $"{latestValue:0.000}";
            nextDataIndex += 1;
        }

        void Render(object sender, EventArgs e)
        {
                wpfPlot1.plt.AxisAuto();
            wpfPlot1.Render(skipIfCurrentlyRendering: true);
        }

        private void DisableAutoAxis(object sender, RoutedEventArgs e)
        {
            wpfPlot1.plt.AxisAuto(verticalMargin: .5);
        }
    }
```

**Comment by swharden** [comment] 2021-02-10 00:33
Hi @saklanmazozgur,

I notice two large programs with your code. First, you must only call `PlotSignal()` one time. In your code you call it multiple times. The correct way to do this is to call it once (passing in an array) then later if the data changes, modify the values in the array and request a new render. The second issue is that you put your code in a try/catch block, so we cannot debug what is wrong.

For real-time highspeed updates of signal plots, you may find this demo helpful to review
https://github.com/swharden/FftSharp#microphone-demo

https://github.com/swharden/FftSharp/blob/1e623b5aab99dbb60231a933c740b3df138caee2/src/FftSharp.Demo/FormMicrophone.cs#L1-L103

Hope it helps!
Scott

**Comment by swharden** [comment] 2021-02-10 00:42
After thinking about it some more, here is an alternative option which may be simpler.

In ScottPlot 4.0, use a scatter plot instead of a signal plot.

In ScottPlot 4.1, you can create a Point plot which might be even easier if you just want to show a single point! This way you won't have to use arrays at all. https://swharden.com/scottplot/cookbooks/4.1.6-beta/category/plottable-point/#point


```cs
// ScottPlot 4.0 example
//  I'm writing it in the browser so it may not be close, but I hope it conveys the idea.
PlottableScatter Scatter;
private void Init()
{
    // create the scatter plot only once
    double[] xs = new double[1];
    double[] ys = new double[1];
    Scatter = Angle_Angle1_Graphic.plt.PlotScatter(xs, ys);
}

private void DispactherTimer_Tick(object sender, EventArgs e)
{
    // update the scatter plot's values whenever the data changes
    dateTime = dateTime.AddMilliseconds(100);
    Scatter.xs[0] = dateTime.ToOATime();
    Scatter.ys[0] = Convert.ToDouble(angle1.Text);
    Angle_Angle1_Graphic.plt.AxisAuto(); // I'm not sure what happens here if you only have 1 point
    Angle_Angle1_Graphic.Render();
}
```

**Comment by saklanmazozgur** [comment] 2021-02-10 06:11
Hello @swharden 

 Thank you for your answer. It was an unsuccessful attempt for me. Running the code below does not give any error but it doesn't run the other code below. (Not in Try catch.)

If the graph is then zoomed, it gives the error "The parameter is not valid". **I do not get such an error when I make the size of the array 2.**

In addition, what I want to do. Sequentially printing the incoming data every 100 milliseconds. As with Growing Data, it must be a constantly flowing data.

The example above is similar to the one that constantly refreshes data or did I get it wrong

**Comment by saklanmazozgur** [comment] 2021-02-10 07:48
Hello @swharden ,

I did something like the following with reference to the example you shared. The only problem here is; Since the array is not full after the last value, it shrinks itself to 0. I shared it as a picture and I placed the relevant field in red. 

How can I solve this problem.

I couldn't upload images due to a problem with Github. I also shared it on an image upload site. For your information.

https://ibb.co/mJVqjY6

Thanks.

**Comment by swharden** [comment] 2021-02-10 19:27
Hi @saklanmazozgur, 

The issue is that you have created large arrays for X and Y data (where all values are instantiated at `0`), but have only partially filled those arrays. When you go to plot them, many of the points are `(0, 0)`. Here are two strategies you may find helpful:

One option would be to use the brand new `Scatter.MaxRenderIndex = lastIndexToDisplay` that was just added this week. It's so new it's not on NuGet yet, so you'd have to download this repo and use ScottPlot from source. This lets you load a big array and define which index range should actually be rendered.

Another option is to use a Signal plot, which already has `MaxRenderIndex` functionality. This would require every X data point to be evenly spaced though, which may or may not be ok for your use case.

Perhaps the best option is to create a `ScatterPlotList` instead of a regular `ScatterPlot`. The `ScatterPlotList` list has methods to add additional data points, and it uses a `List` under the hood to keep track of the data it's plotting.

I suspect all 3 of these ideas could work so I'll close this issue, but feel free to continue to reply if you have further questions or open it up again if you hit a snag! Good luck!

**Closed by swharden** 2021-02-10 19:27 UTC
Labels: Question

**Comment by saklanmazozgur** [comment] 2021-02-11 06:57
Hi @swharden ,

I was using version 4.0.48. I decided to upgrade to version 4.1 to fix the problem we were talking about. However, when trying to edit the menu of the graph in version 4.1, it gives an error.

I will probably use the Signal plot. I think I can overcome the problem with it.

Know the problem with the menu. Thank you for your attention.

 Example ; 

AxisX_Graphic.ContextMenu.Items.Clear();


```
Error: System.NullReferenceException: 'Object reference not set to an instance of an object.'

System.Windows.FrameworkElement.ContextMenu.get returned null.
```
