### ISSUE TITLE
WinUI: right-click menu opens at wrong location (only when display scaling is used)

### ISSUE THREAD

**Issue by EmilNostbakken** [ScottPlot/ScottPlot#3893] opened 2024-06-03 13:28 UTC
**Issue:** When right-clicking in the plot window, the menu doesn't align with the mouse position. Scaling issue?

**ScottPlot Version:** ScottPlot.WinUI 5.0.34

**Comment by swharden** [comment] 2024-06-04 01:06
Thanks for reporting this!

Does the behavior improve if you use 100% display scaling?

https://community.microcenter.com/kb/articles/746-how-to-adjust-display-scaling-in-windows-11

**Comment by VibrationAnalystCN** [comment] 2024-06-04 01:33
100%，125% and 150% Tested, everything is correct.

**Comment by EmilNostbakken** [comment] 2024-06-05 07:21
> Thanks for reporting this!
> 
> Does the behavior improve if you use 100% display scaling?
> 
> https://community.microcenter.com/kb/articles/746-how-to-adjust-display-scaling-in-windows-11

Yes, it works perfectly when I use 100% display scaling.

**Comment by EmilNostbakken** [comment] 2024-06-05 09:04
Tried creating a new project, following the steps in https://scottplot.net/quickstart/winui/. The issue is still there.

**Comment by swharden** [comment] 2024-06-07 14:51
> Yes, it works perfectly when I use 100% display scaling.

Re-stating the problem: "When using the WinUI control, the right-click menu deploys at the wrong location only when display scaling is enabled."

The hard part is that [EmilNostbakken](https://github.com/EmilNostbakken) is reporting this issue but [VibrationAnalystCN](https://github.com/VibrationAnalystCN) is unable to reproduce it. I'll try it on my computer shortly and if I can't reproduce the problem either I'll probably have to close this issue until someone can offer more insight into how to reproduce the issue

**Comment by swharden** [comment] 2024-06-10 21:50
The sandbox app in the main project works for me when display scaling is enabled.

I'll close this issue for now, but if someone can provide a code sample which helps us reproduce the issue we can take a closer look 👍 

![scale-works](https://github.com/ScottPlot/ScottPlot/assets/4165489/24435510-d532-4fb2-92c0-adb728a82186)

**Closed by swharden** 2024-06-10 21:50 UTC
Labels: ⚠️ HIGH PRIORITY
