### ISSUE TITLE
Call Render() automatically when plottable content (not count) changes

### ISSUE THREAD

**Issue by bftrock** [ScottPlot/ScottPlot#1087] opened 2021-05-28 12:01 UTC
**ScottPlot Version:** 4.1.15

**Operating System:** Windows 10

**Application Type:** WinForms

**Bug Description:** First signal selected renders as expected. Updating a plot with a different signal does not cause the plot to re-render (i.e. first signal continues to be displayed). If I change the *number* of signals (e.g. I select 2 signals), it *does* re-render.

**Reproducing:** See code sample below.

```cs
// ListBox control fires this event. Multiple selections allowed. Fires as expected.
private void SignalLb_SelectedIndexChanged(object sender, EventArgs e)
{
    var lb = (ListBox)sender;
    List<string> selectedSignals = new();
    foreach (var item in lb.SelectedItems)
    {
        var signalName = item.ToString();
        selectedSignals.Add(signalName);
    }
    var rtData = SocketClient.GetRealTimeDataResponse(selectedSignals.ToArray(), 60);
    var plot = TrendPlot.Plot;
    plot.Clear();
    plot.XAxis.DateTimeFormat(true);
    plot.Legend(true, ScottPlot.Alignment.UpperLeft);
    foreach (var signal in rtData.Values)
    {
        AddSignalToPlot(signal.Key, signal.Value);
    }
    plot.Render();
}

private void AddSignalToPlot(string name, Dictionary<DateTime, object> data)
{
    var plot = TrendPlot.Plot;
    try
    {
        double[] xs = data.Select(x => x.Key.ToOADate()).ToArray();
        double[] ys = data.Select(x => Convert.ToDouble(x.Value)).ToArray();
        var scatter = plot.AddScatter(xs, ys, label: name);
    }
    catch (Exception ex)
    {
        MessageBox.Show($"Error while plotting signal: {ex.Message}", "Plot Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
    }
}
```

**Comment by swharden** [comment] 2021-05-28 23:19
Hi @bftrock, thanks for sharing this issue!

## Explanation

> Updating a plot with a different signal does not cause the plot to re-render

> If I change the number of signals (e.g. I select 2 signals), it does re-render

This is actually the intended behavior of ScottPlot. I welcome input on how to make this more discoverable or better documented! This is what's happening:

* Any time the user updates the plot (styling or data inside an existing plottable) they must manually call `formsPlot1.Render()` to request a redraw. Giving the user full control of when renders occur allowing maximum performance, as renders only occur when they are intended.

* One exception is when the number of plottables changes. The control checks every 10ms and if the number changes it requests a render automatically. This behavior can be overridden with `formsPlot1.Configuration.RenderIfPlottableCountChanges`.

> Updating a plot with a different signal

This isn't changing the number of plottables, so it's not re-rendering automatically.

## Improvement

I recognize this "render if count changes" thing is confusing, and there could be room for improvement here. It would be nice if a render would occur if _any_ plottables change (not just the number of plottables). Perhaps I can make a special hash code that represents the composition of all plottables, and if _that_ changes it will re-render. I'll look into this! #1028

## Bug Fix

I just realized `RenderIfPlottableCountChanges` isn't being checked in `RenderIfPlottableCountChanged()` 🤦

https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/ScottPlot/Control/Configuration.cs#L107-L110

https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/ScottPlot/Control/Backend.cs#L394-L404

I'll fix this bug now 😅 #1028

**Comment by bclehmann** [comment] 2021-05-29 01:13
I think calling render automatically is nice but checking so often has performance implications.

Getting a hash of all of the plottables which are present (without checking their fields/properties) is not too bad, especially if plots are given an ID field (this was talked about but I can't remember if it was implemented). One can also get an ID-like number based on their memory addresses, but these can be reused if garbage collection happens at exactly the wrong time.

I think rather than computing this hash we should just mark the bitmap as dirty and request a render anytime things like `Plot.Add()` or `Clear()` are called. It's more performant and simpler. This of course doesn't work if you want to extend this to checking if any of the fields have changed, but I think that's quite a bit of work to implement/maintain and also bad for performance.

Plus checking if the data has changed is computationally intractable, so now you've introduced an inconsistency into your API which may well catch users out. Unless you were to mark the bitmap dirty in an update method?

In my opinion, the fact that this option exists but only requests renders in a small subset of situations is confusing and causes issues like this where the user was unaware that they should rerender because it's necessary but not *always* necessary. This makes me wonder if the feature should be removed, or extended so as to be more consistent.

**Comment by swharden** [comment] 2021-05-29 02:14
Thanks for your feedback @bclehmann! This was helpful to think about.

## How to identify plottables

> if plots are given an ID field

I'm reminded that this topic came up before - in #695 string IDs were suggested as a way to track plottables in listboxes

> one can also get an ID-like number based on their memory addresses

I was thinking about using a `Guid`

* https://docs.microsoft.com/en-us/dotnet/api/system.guid.newguid
* https://devblogs.microsoft.com/oldnewthing/20080627-00/?p=21823

It looks like they're unique even when called in rapid succession.

This is easy enough to add to add if it's ever needed.

## Intercept plottable list modifications

> request a render anytime things like Plot.Add() or Clear() are called

This is the simplest and probably best for performance. I'll do this 👍 

## Consistency

> In my opinion, the fact that this option exists but only requests renders in a small subset of situations is confusing and causes issues like this where the user was unaware that they should re-render because it's necessary but not always necessary. This makes me wonder if the feature should be removed, or extended so as to be more consistent.

This is very well stated, and a concern I've had for some time.

I suspect most of the time (>90%?) users just plot data and don't modify plottables' data/style after adding them to the plot. In these situations with the current system users never have to call `Render()`, and it just works.

Maybe we can enforce consistency by keeping it like it is, and stick with "whenever a plottable or its data is modified after adding it to the plot you must request a render manually".

**Comment by swharden** [comment] 2021-05-29 03:25
> request a render anytime things like Plot.Add() or Clear() are called

I ended-up putting together something along these lines:

* I converted `Plottables` from a `List<T>` to an `ObservableCollection<T>`

* I added a function to the `Plottables.CollectionChanged` event handler to modify a public value whenever the list is modified

* Whenever that value is checked by a control and it's different from last time, an automatic render occurs

**Comment by bclehmann** [comment] 2021-05-29 03:43
> It looks like they're unique even when called in rapid succession.

You are correct, GUIDs/UUIDs are often used as the primary keys in databases (or ID or similar thing in non-relational DBs) because they are considered to be unique, even across tables or servers. There's a whole debate over integer vs GUID vs string primary keys and their implications, especially around their performance as clustering keys. It's a google rabbithole that's come up surprisingly often for me recently.

They're considered to be unique because they're 128 bit numbers, so when properly generated the chances of repetition are beyond miniscule.

As for the `CollectionChanged<T>`, that's nice, I hadn't known there was a built in class. Probably makes more sense to have it on the object rather than requiring us to remember to keep track of it ourselves.

**Comment by EmanuelFeru** [comment] 2021-05-29 06:43
I got new information in this discussion and I might have similar or related bug in my case (could be that your change Scott will fix it, I am not sure..).

At Initialization I add 3 Vertical axes each on a different plot. If  do `.Render()` after each of them then they all show up, but if I don't Render, knowing that Scottplot will redender for me, then I have the behavior below. Red line in the first top plot does not show up and the plot appears not to be linked with other plots. Actually, nothing happens with that plot even if I add new signals, it will not move... seems like it really needs one Render to get it going.

So not sure, do I need to Render or it is supposed that ScottPlot will do it for me in this case?

Red = Left Click, Blue = Righ Click

https://user-images.githubusercontent.com/24780745/120060668-58d66500-c059-11eb-8dda-d167cfa3237e.mp4


>I suspect most of the time (>90%?) users just plot data and don't modify plottables' data/style after adding them to the plot. In these situations with the current system users never have to call Render(), and it just works.

I am part of the 10% :-) #1062 However, I confim that is ok **not** to call `.Render()` when I add signals. It's just a matter of being informed to not do it twice.

**Closed** 2021-05-29 21:18 UTC
Labels: BUG

**Comment by bftrock** [comment] 2021-05-31 16:51
Thanks for the attention, @swharden ! Using the `Render` call after modifying the plot fixes the behavior for me, as you suggested. I'm not sure of the best way to document it. Also, this is a great addition to the CS community, so thanks for your effort!
