### ISSUE TITLE
Some invalid SVG Xml is getting generated.  

### ISSUE THREAD

**Issue by aespitia** [ScottPlot/ScottPlot#3907] opened 2024-06-05 19:32 UTC
**Issue:** looks like the "g" tag getting rendered in SVG XML is generating as an unclosed tag, which is making the XML invalid.  

**ScottPlot Version:** 5.0.34

**Code Sample:** See https://github.com/ScottPlot/ScottPlot/assets/105309364/29bdd499-1f8e-40c7-8cf5-d3bd8ea8077a

I will update this hopefully with a code sample if i can figure out how to reproduce it, it's not consistent.

**Comment by aespitia** [comment] 2024-06-05 20:19
``
ScottPlot.Plot myPlot = new();

List<PieSlice> slices = new()
{
	new PieSlice() { Value = 1870, FillColor = Colors.Red, Label = "Cat1" },
	new PieSlice() { Value = 1680, FillColor = Colors.Orange, Label = "Cat2" },
	new PieSlice() { Value = 1400, FillColor = Colors.Gold, Label = "Cat3" },
	new PieSlice() { Value = 1240, FillColor = Colors.Green, Label = "Cat4" },
	new PieSlice() { Value = 1000, FillColor = Colors.Blue, Label = "Cat5" },
	new PieSlice() { Value = 980, FillColor = Colors.Blue, Label = "Cat6" },
	new PieSlice() { Value = 940, FillColor = Colors.Blue, Label = "Cat7" },
	new PieSlice() { Value = 430, FillColor = Colors.Blue, Label = "Cat8" },
	new PieSlice() { Value = 880, FillColor = Colors.Blue, Label = "Cat9" },
	new PieSlice() { Value = 610, FillColor = Colors.Blue, Label = "Cat10" },
};

var pie = myPlot.Add.Pie(slices);
myPlot.HideGrid();
myPlot.Layout.Frameless();

//I believe this is the thing that causes the invalid xml, hiding the legend
myPlot.HideLegend();

pie.DonutFraction = .6;
//produces invalid xml, the "g" tag is not closed
var xml = myPlot.GetSvgXml(400,300);
//produces valid xml where the "g" tag is closed after the paths
myPlot.SaveSvg("c:\\temp\\pie-svg-bug.svg", 400, 300);

//if you paste this xml into a blank text file and save as SVG, you'll see it's invalid
xml.Dump();
``

**Comment by aespitia** [comment] 2024-06-05 20:22
![image](https://github.com/ScottPlot/ScottPlot/assets/105309364/1432d80b-d25f-4cf9-9bd0-9481d711e11c)
![image](https://github.com/ScottPlot/ScottPlot/assets/105309364/94dcbe32-e56c-4a84-b6fa-c819a73daa2f)

**Comment by swharden** [comment] 2024-06-06 03:05
Looking at the SVG XML...

```xml
<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1000" height="750">
	<rect transform="scale(2 2)" width="1000" height="750"/>
	<rect fill="white" transform="scale(2 2)" width="1000" height="750"/>
	<clipPath id="cl_c">
		<rect width="1000" height="750"/>
	</clipPath>
	<g clip-path="url(#cl_c)">
		<path ... />
		<path ... />
		<path ... />
</svg>
```

It looks like a `g` element with clipping is applied but never removed. I'm concerned this may be a bug with SkiaSharp (not ScottPlot) but some trial and error work figuring out exactly which shape, transformation, or clip in the pie chart causes this issue would be a good start, then create a minimal code example using SkiaSharp (not ScottPlot at all) reproducing it would help confirm whether it's a SkiaSharp bug.

Here's some code from #2704 to get started:
```cs
void DemoLines(int width = 400, int height = 300, string saveAs = "lines.svg")
{
    using FileStream fs = new(saveAs, FileMode.Create);
    using SKCanvas canvas = SKSvgCanvas.Create(new SKRect(0, 0, width, height), fs);
    canvas.Clear(SKColors.Navy);

    using var paint = new SKPaint() { IsStroke = true };
    for (int i = 0; i < 100; i++)
    {
        paint.Color = RandomColor();
        canvas.DrawLine(
            x0: Rand.Next(width),
            y0: Rand.Next(height),
            x1: Rand.Next(width),
            y1: Rand.Next(height),
            paint: paint);
    }
}
```

I'll close this issue for now, but if we determine it's something we can fix from inside ScottPlot we can open it back up again and give it a go! 👍

**Closed by swharden** 2024-06-06 03:05 UTC

**Comment by aespitia** [comment] 2024-06-06 13:10
what's weird though is that the code above, if you save the svgxml, it does have the closing "g" tag properly, but if you look at the returned XML it doesn't.  but what's even weirder to me now, is that i looked at the SaveSvg implementation, and it looked like it was just pulling the same GetSvgXML itself, and then saving it...very strange
