### ISSUE TITLE
How to display live data (a plot that updates itself) using WPF

### ISSUE THREAD

**Issue by roycirkin** [ScottPlot/ScottPlot#907] opened 2021-03-28 09:03 UTC
hi, I have an application that updates the ScottPlot WPF object every time when an event happens. the problem is that I have to click on the graph in order to see the updated graph. is there any way to make the graph refresh itself without the click on the graph by the user? thanks! this is the updating code:
```
                    graph1.Plot.Clear();
                    graph2.Plot.Clear();
                    int len = vm_graphs.VM_Line;
                    double[] arr = new double[len];
                    double[] arr1 = new double[len];
                    double[] arr2 = new double[len];
                    vm_graphs.VM_LineList.GetRange(0,vm_graphs.VM_Line).ToArray().CopyTo(arr, 0);
                    vm_graphs.VM_FullValuesArray.GetRange(0, vm_graphs.VM_Line).ToArray().CopyTo(arr1, 0);
                    vm_graphs.VM_FullCorellativeValuesArray.GetRange(0, vm_graphs.VM_Line).ToArray().CopyTo(arr2, 0);
                    graph2.Plot.AddScatter(arr, arr2);
                    graph1.Plot.AddScatter(arr, arr1);
                    graph1.Plot.AxisAuto();
                    graph2.Plot.AxisAuto();
                    graph1.Plot.Render();
                    graph2.Plot.Render();
```

**Comment by FoggyFinder** [comment] 2021-03-28 09:11
Seems like it is a duplicate of #905

**Comment by roycirkin** [comment] 2021-03-28 10:09
> Seems like it is a duplicate of #905

hi, I switched "graph1.plot.Render()" to "graph1.Render()", but the graph still doesn't update itself, only when I click on it. any other ideas why it does not work? isn't there a way to make the graph think that I clicked on him every time I call this updating function? (maybe invoke the clickEventHandler from the code)

**Comment by FoggyFinder** [comment] 2021-03-28 10:42
any chance you can create a small sample that reproduce this behaviour?

**Comment by roycirkin** [comment] 2021-03-28 13:14
> any chance you can create a small sample that reproduce this behaviour?

the main idea is that the graph is getting notifications every time a property changes (the property is an array of doubles) and when it changes the graph should take that array and print it on the screen (the goal is to make it update itself every time that property changes).  the only problem is that I have to click on him in order to see the new graph..

` if (e.PropertyName == "VM_Line")
                {
                    try
                    {
                        updateGraphs();
                    }`
`private void updateGraphs()
        {
            if (vm_graphs.VM_CurrentProperty != null)
            {
                try
                {
                    graph1.Plot.Clear();
                    graph2.Plot.Clear();
                    int len = vm_graphs.VM_Line;
                    double[] arr = new double[len];
                    double[] arr1 = new double[len];
                    double[] arr2 = new double[len];
                    vm_graphs.VM_LineList.GetRange(0, vm_graphs.VM_Line).ToArray().CopyTo(arr, 0);
                    vm_graphs.VM_FullValuesArray.GetRange(0, vm_graphs.VM_Line).ToArray().CopyTo(arr1, 0);
                    vm_graphs.VM_FullCorellativeValuesArray.GetRange(0, vm_graphs.VM_Line).ToArray().CopyTo(arr2, 0);
                    graph2.Plot.AddScatter(arr, arr2);
                    graph1.Plot.AddScatter(arr, arr1);
                    graph1.Plot.AxisAuto();
                    graph2.Plot.AxisAuto();
                    graph1.Render();
                    graph2.Render();
                }`

**Comment by swharden** [comment] 2021-03-28 16:39
Hi @roycirkin,

I notice your render code is in a try/catch block. Is there a chance it is throwing an exception and exiting the block before `Render()` is called?

Downloadable examples of live, updating data plots can be found on 
https://swharden.com/scottplot/faq/live-data/

Hope it helps!
Scott

**Closed** 2021-03-28 16:41 UTC
Labels: Question
