### ISSUE TITLE
Zoom Bug - Lines are turning solid when set to Dashed (or anything that isn't solid)

### ISSUE THREAD

**Issue by RB275** [ScottPlot/ScottPlot#4222] opened 2024-09-06 15:51 UTC
**Issue:** I encountered an issue where zooming in/out will cause a line dashed line to turn into a solid line past a certain zoom level.
This is also possible to encounter when using the middle-click range zoom. Zooming out turns the line back into a dash.

**ScottPlot Version:** 

```
<PackageReference Include="ScottPlot" Version="5.0.37" />
<PackageReference Include="ScottPlot.WPF" Version="5.0.37" />
```

https://github.com/user-attachments/assets/9b2e3509-fc44-49d6-aa0b-06414b5ba9f1

Github appears not to like any OBS recording I put up, but windows plays it just fine:
[ScreenRecording.zip](https://github.com/user-attachments/files/16910344/ScreenRecording.zip)

**Code Sample:** This was zooming in and out using native functionality in the wpf app.

<details>
<summary >The lines are generated like so:</summary>

```cs
public DataPointSource? Render(PlotHelper plotHelper)
{
    if (!IsVisible) return null;

    // setup the Y axis
    var plot = plotHelper.Plot;
    var color = (LineColor ??= ColorViewModel.GetNextColor(plotHelper)).ScottPlotColor;

    IYAxis yAxis;
    if (Slot.SignalType is SignalType.Input or SignalType.Output)
    {
        yAxis = plotHelper.BooleanAxis;
    }
    else if (Slot.SignalType is SignalType.VacuumLevel)
    {
        yAxis = plotHelper.VacuumAxis!;
    }
    else
    {
        if (plotHelper.IsFirstLeftAxisUsed)
        {
            yAxis = new ScottPlot.AxisPanels.LeftAxis();
            plot.Axes.AddLeftAxis(yAxis);
        }
        else
        {
            yAxis = plot.Axes.Left;
            plotHelper.IsFirstLeftAxisUsed = true;
        }

        yAxis.Label.Text = ChartDisplayName;
        yAxis.Label.ForeColor = color;
        yAxis.IsVisible = yAxis == plot.Axes.Left || yAxis == plot.Axes.Right || ShowAxisLabel;

        switch (Slot.SignalType)
        {
            case SignalType.Counter:
                yAxis.TickGenerator = new ScottPlot.TickGenerators.NumericAutomatic() { IntegerTicksOnly = true };
                break;

            case SignalType.VacuumLevel:
                
                break;

            case SignalType.AxisCurrent:
            case SignalType.AxisData:
                yAxis.Label.Text = $"{ChartDisplayName} {(Slot.Unit == RecordUnit.UNITMM ? "(mm)" : "")}";
                break;
            
            default:
                break;
        }
    }

    // setup the plot
    switch (Slot.RecordMode)
    {
        case RecordMode.Poll:
            var signal = plot.Add.SignalXY(Slot.TimeStamps, Slot.Values, color);
            signal.Axes.YAxis = yAxis;
            signal.LegendText = DisplayName;
            signal.LinePattern = LinePattern;
            return _dataPointSource = new DataPointSource(this, signal);

        case RecordMode.Edge:
            Coordinates? prevCoordinate = null;
            List<double> x = new List<double>();
            List<double> y = new List<double>();
            for (int i = 0; i < Slot.TimeStamps.Length; i++)
            {
                Coordinates prev = prevCoordinate ?? default;
                var cord = new Coordinates(Slot.TimeStamps[i], Slot.Values[i]);

                // check to create a vertical line as the edge
                if (i > 0 && cord.Y != prev.Y)
                {
                    x.Add(cord.X);
                    y.Add(prev.Y);
                }
                // current coordinate
                x.Add(cord.X);
                y.Add(cord.Y);

                prevCoordinate = cord;
            }

            // horizontal line until end of graph
            if (prevCoordinate is Coordinates last)
            {
                x.Add(plotHelper.MaxXY.X);
                y.Add(last.Y);
            }

            var scatter = plot.Add.ScatterLine(x, y, color);
            scatter.Axes.YAxis = yAxis;
            scatter.LinePattern = LinePattern;
            scatter.LegendText = DisplayName;
            return _dataPointSource = new DataPointSource(this, scatter);

        default:
            throw new NotImplementedException($"Unknown Recording Mode : {Slot.RecordMode}");
    }
}
```
</details>

**Comment by Chad-V** [comment] 2024-10-16 20:30
I was just reviewing a similar problem I'm having. I'm not sure exactly, but I think it's a result of Signal.RenderHighDensity? The dashes are the exact same size regardless of the zoom level until I hit multiple data points per pixel, which triggers RenderHighDensity, and the dash setting is immediately lost and it starts to draw as a solid line. My suspicion is that it's caused by the path.LineTo -> path.MoveTo loop at the bottom of the function, but I'm not sure a good solution exactly for it.

**Comment by RB275** [comment] 2024-10-19 14:45
So in my scenario, the issue was definitely not to do with multiple data points per pixel. 
My square wave shown has 1 data point per corner, and thats it. 

for example:
|start    |Corner1| Vertical (UP)|Horizontal |vertical (DOWN)|Continue to edge|
|---|---|---|---|---|---|
|(0,0)     |(100,0)  |  (100,1)   |(200,1)   |(200,0)|   (300,0)|

**Comment by Chad-V** [comment] 2024-10-24 13:20
Having a bit of a closer look, it runs RenderHighDensity when the visible x range span, divided by the total data width, divided by the space between data points, is at least 1, and RenderHighDensity draws lines to connect the top and bottom of any "pixel column", where any two Y points share the same X **pixel** (not data). Which looks like it's still the cause of both of our problems.

It's still unclear to me why the draw call doesn't utilize the dashed line paint, though, so I'm not positive the solution.

**Comment by swharden** [comment] 2024-11-08 02:56
> Looks like using the stroke cap Square or Round could cause these problems, but definitely needs a bit more investigation. I'll test using a different stroke cap when I have the chance.

I'll close this issue for now, but if a solution is reached we can open it back up and discuss how to correct it!

If someone creates a PR to fix this issue, I will be happy to review it an merge it in quickly.

I probably won't start working on this myself soon because I can tell this is the type of issue that you can get sucked into for a very long time 😅 

Thanks for reporting this issue, and for your comments along the way!

**Closed by swharden** 2024-11-08 02:56 UTC

**Comment by Chad-V** [comment] 2024-11-26 18:20
Re: a problem that you can get sucked into for a very long time. Yes, indeed!

I've dug a bit more into this. It's interesting, because it's two separate problems, as Signal (what I saw this bug in) and SignalXY use completely different render paths. But they may be the same idea.

Reproducing this issue with both Signal and SignalXY, I'm still not sure exactly what is happening or where the breakdown is occurring, but I can see that there are many offscreen pixels being passed to the Skia renderer for both, when these artifacts begin showing up. Specifically, there are points being drawn billions of pixels off the screen, usually in the Y direction.

At the moment between drawing a solid line and a dashed line, I also noticed that the maximum range between two drawn-offscreen pixels crossed the 8billion threshold. Before zooming in, it's dashed and good, but after zooming in, it's solid and has two pixels with a line drawn between them (offscreen) that is > 8 billion pixels long.

I haven't yet worked through if clamping those pixels out will fix it, but that feels an oversight regardless. Both SignalXY and Signal, in their own clamping patterns, only clamp pixels in the X range, and never seem to clamp pixels in the Y range. SignalXY has interpolation performed in SignalXYSourceDoubleArray.GetPixelsToDraw() (or similar ISignalXYSource classes), but it's only done in the X direction (or in the Y direction when rotated, which has the same effect of interpolation only happening in one range). Signal.GetVisibleXRange() does the same thing, without any interpolation at all for off-screen artifacts, and only testing if a point's X value is within the drawn rectangle and never the Y value.

While I'm a little suspicious this may be causing the issue at hand, it's also certainly a large performance drain. For a regular Signal with some noise, after zooming in so 0 points are on screen and only one intersecting line is visible, it was still running calculations and render calls on hundreds of points. I think the current process (ignoring the Y values) is used to ensure the lines between offscreen points are visible if they intersect the drawn canvas.

If I come up with a solution in the coming weeks when I have time to pick at this, I'll set up a PR and let you know!

**Comment by RFBomb** [comment] 2024-11-26 19:28
```cs

//pulled from Signal

   private CoordinateRange GetVisibleXRange(PixelRect dataRect)
    {
        // TODO: put GetRange in axis translator
        double xViewLeft = Axes.GetCoordinateX(dataRect.Left);
        double xViewRight = Axes.GetCoordinateX(dataRect.Right);
        return (xViewLeft <= xViewRight)
            ? new CoordinateRange(xViewLeft, xViewRight)
            : new CoordinateRange(xViewRight, xViewLeft);
    }
```

My gut says this might have to do with what I was running into for IGetNearest. The data rectangle parameter might not be correct for this plottable's assigned axes, which results in the calculation being incorrect. You may want to backtrack where the parameter comes from as a first line of inquiry if this method is the culprit is your line of thinking
