### ISSUE TITLE
ScottPlot.OpenGL

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2399] opened 2023-02-18 22:21 UTC
Create a NuGet package to contain OpenGL plottables and helper methods

* #2397
* #2383

**Comment by StendProg** [comment] 2023-02-19 19:34
Hi @swharden,

I already thought about it, but there is a problem.
We actually need 2 versions of this package. One version is built on a dependency on OpenTK 2.0 and another on OpenTK 3.0. Versions of the OpenTK API have differences, but at first glance they are not critical. So I think we can get by with one code base and conditional operators in some places. But how to organize it and how it will look, here I am lost, there is little experience with Nuget.

Why is this needed?
1. Winforms control is built on a dependency on OpenTK 2.0.
2. WPF NET462 is built on dependence on OpenTK 2.0.
3 WPF NETCORE is built on a dependency on OpenTK 3.0.

If we try to add package built on OpenTK 2.0 to the WPF NETCORE control, then we get the `cousin dependencies` problem, which, as I understand it, has no solution using Nuget.

**Comment by swharden** [comment] 2023-03-18 18:39
Hi @StendProg, I think this is easier now that the Windows Forms control uses OpenTK 3

https://www.nuget.org/packages/SkiaSharp.Views.WindowsForms#dependencies-body-tab

![image](https://user-images.githubusercontent.com/4165489/226129466-ac6bd91f-12d3-4b3f-a3fb-7aa516387ea5.png)

I'm moving all the OpenGL code out of the WinForms control and into its own project (#2496). I'll publish it as a separate NuGet package when I make the next ScottPlot 5 release. I think this solves our issues, but if there's a case I did not think of let me know and I can work to improve it or roll the changes back.

**Comment by StendProg** [comment] 2023-03-19 14:58
Hi @swharden,

My bad. When I wrote 2 I meant 3, when I wrote 3 I meant 4 (the SciaSharp version must have confused me).

Simply put, the problem is in this code:
https://github.com/ScottPlot/ScottPlot/blob/33fca4cbcb884161d61e05615604b008a0e7aac1/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WPF/ScottPlot.WPF.csproj#L39-L46

SKGLElement uses OpenTK4 for modern .NET.
All other controls use OpenTK3.
We can of course try to downgrade, but only as long as we have control over this component. When it will be included in SkiaSharp, we won't have this option

**Comment by swharden** [comment] 2023-04-02 21:26
> SKGLElement uses OpenTK4 for modern .NET.
> All other controls use OpenTK3.

I suspect that with more time new SkiaSharp controls will eventually all use OpenTK4 

I'll probably keep OpenGL code isolated in its own package (like it is now) but not publish it on NuGet until this gets worked out. I don't think I should devote too much of my time right now into creating and maintaining OpenGL plot types, but these resources will be available for anyone who wants to look into it further, and will also be in a good place to resume development if all SkiaSharp controls start using the same OpenTK version in the future.

Thanks again for all your help on this!

**Closed** 2023-04-02 21:27 UTC
Labels: ⚠️ HIGH PRIORITY
