### ISSUE TITLE
Histogram bins/counts should be identical to similar libraries (numpy)

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#1051] opened 2021-05-21 14:47 UTC
### Your Environment
- ScottPlot Version: 4.1.12
- Operating System:W10
- Is it a GUI app? What platform? Winforms

Describe the bug and how we can reproduce it.

Ive got an issue when drawing histograms and a normal distribution curve. Notice where the distribution curve cuts off at 3.45. There is supposed to be a bin there with a height of 1. I am clueless as to why scottplot is not drawing the bin. Looking in my plottable variables, the data is there. Everything seems to be correct but it is just not drawing it. I am clueless as to why. I cannot find a pattern as to why this happens. BUT it ALWAYS happens on the right hand side of the graph. 
![image](https://user-images.githubusercontent.com/81701546/119155464-228e5980-ba4b-11eb-81a2-7ebc42f06be6.png)

Another example. 0.2870 is a bin with a count/height of 3
![image](https://user-images.githubusercontent.com/81701546/119155879-89ac0e00-ba4b-11eb-8fbb-a17919754ddc.png)

But then here is one which is drawn correctly. 
![image](https://user-images.githubusercontent.com/81701546/119156127-d55eb780-ba4b-11eb-9ebc-1900d424afb5.png)

The code behind all these examples are the exact same. The only difference is the values in the array. All examples are being fed with an array size of 32
Any clue as to how I can begin to troubleshoot this?

```cs
public void PlotHistoGramAndNormalDistribution(List<double> values, ScottPlot.FormsPlot MainPlot)
{

   ScottPlot.Statistics.Histogram histogram = new ScottPlot.Statistics.Histogram(values.ToArray(), values.Min(), values.Max());

    // plot the bins as a bar graph (on the primary Y axis)
    var bar = MainPlot.Plot.AddBar(histogram.counts, histogram.bins, Color.BlueViolet);
    bar.BarWidth = histogram.binSize * 1.1; // oversize to reduce render artifacts
    bar.BorderLineWidth = 0.1F;
    bar.FillColor = ColorTranslator.FromHtml("#9bc3eb");
    bar.BorderColor = ColorTranslator.FromHtml("#82add9");
    bar.YAxisIndex = 0;
    MainPlot.Plot.YAxis.Label("Count (#)");
    MainPlot.Plot.YAxis.Color(ColorTranslator.FromHtml("#82add9"));

    // plot the normal dist curve as a scatter plot (on the secondary Y axis)
    ScottPlot.Plottable.ScatterPlot normalDist = MainPlot.Plot.AddScatter(histogram.bins, histogram.countsFracCurve, 
    Color.Green);
    normalDist.MarkerSize = 0;
    normalDist.LineWidth = 2;
    normalDist.YAxisIndex = 1;
    MainPlot.Plot.YAxis2.Label("Fraction");
    MainPlot.Plot.YAxis2.Color(normalDist.Color);
    MainPlot.Plot.YAxis2.Ticks(true);

    //draw y axis and x axis 0 lines
    MainPlot.Plot.AddHorizontalLine(0, Color.Black);
    

    // decorate the plot
    MainPlot.Plot.XAxis2.Label("Normal distribution", bold: true);
    MainPlot.Plot.SetAxisLimits(yMin: 0);
    MainPlot.Plot.Grid(lineStyle: LineStyle.Dot);

    //a lot of things have changed. we need to re render to apply. Otherwise user has to move mouse on graph for it to 
    refresh
    MainPlot.Render();
}
```

Thanks

**Comment by bclehmann** [comment] 2021-05-21 18:41
Try using this to construct your histogram object:

```cs
ScottPlot.Statistics.Histogram histogram = new ScottPlot.Statistics.Histogram(values.ToArray(), values.Min(), values.Max(), ignoreOutOfBounds: false);
```

If `ignoreOutOfBounds` is false then an extra bin will be added to the left and the right of your distribution. Let me know if this works.

**Comment by breakwinz** [comment] 2021-05-21 19:58
@bclehmann Does indeed work. Thank you! Could you please explain this variable? When would I need to have it as false vs true?

Before:
![image](https://user-images.githubusercontent.com/81701546/119191848-17512300-ba77-11eb-8307-099160602b73.png)

After:
![image](https://user-images.githubusercontent.com/81701546/119191803-0a343400-ba77-11eb-82f2-2a53cfde2f8f.png)

**Comment by bclehmann** [comment] 2021-05-21 21:43
>  Why is it being ignored in this case?

I think because the number of bins to create is getting rounded down, which creates an off-by-one. This is an issue with ScottPlot, not your code.

You can explicitly set the number of bins and their width if you would like with the `binSize` and `binCount` parameters. This gives more finegrained control.

**Comment by swharden** [comment] 2021-05-21 23:20
Hey @breakwinz thanks for reporting this surprising behavior, and @bclehmann for figuring out what's causing it and offering a good suggestion. 

Fundamentally this issue points-out that the histogram's binning behavior may be inaccurate, prone to rounding error, or at best poorly documented and results in surprising behavior. I think a review of the binning/counting system is warranted, and I'd like to add tests which assert the bins/counts determined by ScottPlot are identical to those reported by an established python library like numpy or matplotlib. I added this issue to the triage list #1028 and will return to it after ScottPlot 4.1 is released in the next few days.

An immediate interim solution to achieve total confidence in your output would be to do the mathematical binning/counting yourself (implementing the edge bin behavior you want), then add a bar plot and line plot (or function plot) to the plot, avoiding the need to interact with the Histogram plot type.

**Comment by swharden** [comment] 2021-08-01 17:57
Hi @breakwinz and @bclehmann 👋 thanks for both of your input! This issue has been open for a few months but I finally made some progress here.

ScottPlot isn't intended to be a statistics suite (there are many excellent libraries for this), and I believe the original unexpected behavior slipped through because ScottPlot was trying to do a little too much.

With PR #1166 I marked the `ScottPlot.Statistics.Histogram` module **obsolete** and replaced this functionality with static methods in `ScottPlot.Statistics.Common`. I updated the cookbook examples to use these new methods.

I mimicked the histogram functionality from Numpy (a Python numerical processing library) and wrote tests to ensure the output of these methods are identical to the output of Python. When a range of bins is provided, Numpy **ignores** values outside that range, so that's what ScottPlot does now too. My thinking is that if users need a different type of binning, they are encouraged to write their own histogram/binning function or use an established statistics library for this.

## New (Static) Histogram Method

```cs
(double[] counts, double[] binEdges) = ScottPlot.Statistics.Common.Histogram(values, min, max, binSize);
```

This only produces histograms with evenly-spaced bins. I considered creating an overload which would accept user-defined non-uniform bins, but decided against it because (1) it complicates probability calculations and (2) I really want to encourage users to use "real" statistics libraries for anything other than the most cursory analysis tasks. I think this is an appropriate compromise, but I welcome input. It's still easy to change.

## Multi-Axis Histogram Cookbook Example

![image](https://user-images.githubusercontent.com/4165489/127779917-3c87a2c1-d281-497c-9d63-83f65f8ef2a8.png)

```cs
var plt = new ScottPlot.Plot(600, 400);

// generate sample heights are based on https://ourworldindata.org/human-height
Random rand = new(0);
double[] values = ScottPlot.DataGen.RandomNormal(rand, pointCount: 1234, mean: 178.4, stdDev: 7.6);

// create a histogram
(double[] counts, double[] binEdges) = ScottPlot.Statistics.Common.Histogram(values, min: 140, max: 220, binSize: 1);
double[] leftEdges = binEdges.Take(binEdges.Length - 1).ToArray();

// display histogram probabability as a bar plot
var bar = plt.AddBar(values: counts, positions: leftEdges);
bar.FillColor = ColorTranslator.FromHtml("#9bc3eb");
bar.BorderLineWidth = 0;

// display histogram distribution curve as a line plot on a secondary Y axis
double[] smoothEdges = ScottPlot.DataGen.Range(start: binEdges.First(), stop: binEdges.Last(), step: 0.1, includeStop: true);
double[] smoothDensities = ScottPlot.Statistics.Common.ProbabilityDensity(values, smoothEdges, percent: true);
var probPlot = plt.AddScatterLines(
    xs: smoothEdges,
    ys: smoothDensities,
    lineWidth: 2, 
    label: "probability");
probPlot.YAxisIndex = 1;
plt.YAxis2.Ticks(true);

// display vertical lines at points of interest
var stats = new ScottPlot.Statistics.BasicStats(values);
plt.AddVerticalLine(stats.Mean, Color.Black, 2, LineStyle.Solid, "mean");
plt.AddVerticalLine(stats.Mean - stats.StDev, Color.Black, 2, LineStyle.Dash, "1 SD");
plt.AddVerticalLine(stats.Mean + stats.StDev, Color.Black, 2, LineStyle.Dash);
plt.AddVerticalLine(stats.Mean - stats.StDev * 2, Color.Black, 2, LineStyle.Dot, "2 SD");
plt.AddVerticalLine(stats.Mean + stats.StDev * 2, Color.Black, 2, LineStyle.Dot);
plt.AddVerticalLine(stats.Min, Color.Gray, 1, LineStyle.Dash, "min/max");
plt.AddVerticalLine(stats.Max, Color.Gray, 1, LineStyle.Dash);
plt.Legend(location: Alignment.UpperRight);

// customize the plot style
plt.Title("Adult Male Height");
plt.YAxis.Label("Count (#)");
plt.YAxis2.Label("Probability (%)");
plt.XAxis.Label("Height (cm)");
plt.SetAxisLimits(yMin: 0);
plt.SetAxisLimits(yMin: 0, yAxisIndex: 1);

plt.SaveFig("stats_histogramStdev.png");
```

Note that there's a probability curve generator which returns `Func<double, double?>` but it's surprisingly hard to use because when it's the only thing on the secondary Y axis ScottPlot's auto-scaling doesn't know how to properly scale it. Using a high resolution scatter plot was the simplest option for this cookbook example.

**Closed** 2021-08-01 17:59 UTC
Labels: BUG
