### ISSUE TITLE
custom tick formatter

### ISSUE THREAD

**Issue by danhi** [ScottPlot/ScottPlot#4340] opened 2024-10-14 22:30 UTC
**Question:** In the cookbook about using a custom tick formatter, it has the following code:

```cs
// apply our custom tick formatter
DateTimeAutomatic tickGen = (DateTimeAutomatic)axis.TickGenerator;
tickGen.LabelFormatter = CustomFormatter;
```

When I try to use this in VB.Net, I can't cast it to DateTimeAutomatic.  I can execute

```
axis = plotUsageByDay.Plot.Axes.DateTimeTicksBottom
Dim tickGen As ITickGenerator = axis.TickGenerator
```

(since I can see that DateTimeTicksBottom is of type ITickGenerator), but I can't do the cast to DateTimeAutomatic, as VB doesn't know it.  Normally I would use

```
dim tickGen as DateTimeAutomatic = ctype(axis.TickGenerator, DateTimeAutomatic)
```

but DateTimeAutomatic is unknown.  And if I just try to use

```
axis = plotUsageByDay.Plot.Axes.DateTimeTicksBottom
Dim tickGen As ITickGenerator = axis.TickGenerator
tickGen.LabelFormatter = <my function>
```

```
.LabelFormatter is not a member of tickGen.
```

Can anyone tell me what I am doing wrong?

**Comment by swharden** [comment] 2024-11-08 21:57
Hi @danhi, I think this is a duplicate of #4338. See https://github.com/ScottPlot/ScottPlot/issues/4338#issuecomment-2465810848 for more information.

**Closed by swharden** 2024-11-08 21:57 UTC
