### ISSUE TITLE
Control: Opt-in flag to lock opposing axes together

### ISSUE THREAD

**Issue by rubenslkirchner** [ScottPlot/ScottPlot#3729] opened 2024-04-25 16:10 UTC
**Issue:** When I zoom in on either the top or right axis of the graph, the drawing appears to be incorrect. However, when I zoom inside the graph, it works fine. 

**ScottPlot Version:** 5.0.28

**Code Sample:** 

```cs
using System.Windows;
using ScottPlot;
using ScottPlot.TickGenerators;

namespace trips.playback.plotters.scottplot
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
        }

        private void MainWindow_OnLoaded(object sender, RoutedEventArgs e)
        {
            // plot sample data
            formsPlot1.Plot.Add.Signal(Generate.Sin(51, mult: 100_000));
            formsPlot2.Plot.Add.Signal(Generate.Sin(51, mult: 100_000));

            // add labels
            formsPlot1.Plot.Axes.Left.Label.Text = "Vertical Axis";
            formsPlot2.Plot.Axes.Left.Label.Text = "Vertical Axis";
            formsPlot1.Plot.Axes.Bottom.Label.Text = "Horizontal Axis";
            formsPlot2.Plot.Axes.Bottom.Label.Text = "Horizontal Axis";

            // use a fixed size for the left axis panel to ensure it's always aligned
            float leftAxisSize = 90;
            formsPlot1.Plot.Axes.Left.MinimumSize = leftAxisSize;
            formsPlot1.Plot.Axes.Left.MaximumSize = leftAxisSize;
            formsPlot2.Plot.Axes.Left.MinimumSize = leftAxisSize;
            formsPlot2.Plot.Axes.Left.MaximumSize = leftAxisSize;

            // when one plot changes update the other plot
            formsPlot1.Plot.RenderManager.AxisLimitsChanged += (s, e) =>
            {
                ApplyLayoutToOtherPlot(formsPlot1, formsPlot2);
            };
            formsPlot2.Plot.RenderManager.AxisLimitsChanged += (s, e) =>
            {
                ApplyLayoutToOtherPlot(formsPlot2, formsPlot1);
            };
            
            formsPlot1.Plot.Axes.AutoScale();
            formsPlot2.Plot.Axes.AutoScale();
            
            PrimaryGroup();
            SecondaryGroup();

            // initial render
            formsPlot1.Refresh();
            formsPlot2.Refresh();
        }

        private void PrimaryGroup()
        {
            var newax = formsPlot1.Plot.Axes.Top;
            var customticks = new NumericManual();
            customticks.AddMajor(1, "A");
            customticks.AddMajor(10, "B");
            customticks.AddMajor(50, "C");
            customticks.AddMajor(100, "D");
            customticks.AddMajor(200, "E");

            newax.TickGenerator = customticks;
            
            var serie = formsPlot1.Plot.Add.Signal(Generate.Cos(51, mult:100_000));
            serie.Color = Colors.Red;
            serie.Axes.XAxis = newax;
            serie.Axes.YAxis = formsPlot1.Plot.Axes.Left;
        }
        
        private void SecondaryGroup()
        {
            var serie = formsPlot1.Plot.Add.Signal(Generate.Consecutive(51, 1));
            serie.Color = Colors.Purple;
            serie.Axes.YAxis = formsPlot1.Plot.Axes.Right;
        }

        private void ApplyLayoutToOtherPlot(IPlotControl source, IPlotControl dest)
        {
            AxisLimits axesBefore = dest.Plot.Axes.GetLimits();
            
            dest.Plot.Axes.SetLimits(source.Plot.Axes.GetLimits());
            dest.Plot.Axes.SetLimitsX(source.Plot.Axes.GetLimits());
            dest.Plot.Axes.SetLimitsX(source.Plot.Axes.GetLimits(), dest.Plot.Axes.Top);
            
            AxisLimits axesAfter = dest.Plot.Axes.GetLimits();
            if (axesBefore != axesAfter)
            {
                dest.Refresh();
            }
        }
    }
}
![trips playback plotters scottplot_QD330sd38S](https://github.com/ScottPlot/ScottPlot/assets/7251969/5d17788b-e7dd-41cb-8214-69c1c24e8084)

```

**Comment by rubenslkirchner** [comment] 2024-04-25 16:10
![trips playback plotters scottplot_QD330sd38S](https://github.com/ScottPlot/ScottPlot/assets/7251969/2b9e8907-7bb6-4a2c-b52b-bf4adfccfce3)

**Comment by rubenslkirchner** [comment] 2024-04-26 12:09
@swharden This issue is the most critical because the user can reproduce easily and we don't have any workaround.

**Comment by swharden** [comment] 2024-04-26 12:53
This works for me, let me know if the strategy works for you too!

I changed the logic a bit: (1) I use a timer to manage axis copying and rendering for a little better performance and to ensure one plot isn't modified inside the render loop of another and (2) all axis limits are copied, not just the primary ones

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    readonly System.Windows.Forms.Timer RefreshTimer = new();

    public Form1()
    {
        InitializeComponent();

        // plot 1 signal 1
        var sig1 = formsPlot1.Plot.Add.Signal(Generate.Sin(mult: 0.001));
        sig1.Axes.YAxis = formsPlot1.Plot.Axes.Left;
        sig1.Axes.XAxis = formsPlot1.Plot.Axes.Bottom;
        formsPlot1.Plot.Axes.Color(formsPlot1.Plot.Axes.Left, sig1.Color);
        formsPlot1.Plot.Axes.Color(formsPlot1.Plot.Axes.Bottom, sig1.Color);

        // plot 1 signal 2
        var sig2 = formsPlot1.Plot.Add.Signal(Generate.Cos(mult: 1000));
        sig2.Axes.YAxis = formsPlot1.Plot.Axes.Right;
        sig2.Axes.XAxis = formsPlot1.Plot.Axes.Top;
        formsPlot1.Plot.Axes.Color(formsPlot1.Plot.Axes.Right, sig2.Color);
        formsPlot1.Plot.Axes.Color(formsPlot1.Plot.Axes.Top, sig2.Color);
        formsPlot1.Plot.HideGrid();

        // plot 2 signal 1
        var sig3 = formsPlot2.Plot.Add.Signal(Generate.Sin(mult: 0.001));
        sig3.Axes.YAxis = formsPlot2.Plot.Axes.Left;
        sig3.Axes.XAxis = formsPlot2.Plot.Axes.Bottom;
        formsPlot2.Plot.Axes.Color(formsPlot2.Plot.Axes.Left, sig1.Color);
        formsPlot2.Plot.Axes.Color(formsPlot2.Plot.Axes.Bottom, sig1.Color);

        // plot 2 signal 2
        var sig4 = formsPlot2.Plot.Add.Signal(Generate.Cos(mult: 1000));
        sig4.Axes.YAxis = formsPlot2.Plot.Axes.Right;
        sig4.Axes.XAxis = formsPlot2.Plot.Axes.Top;
        formsPlot2.Plot.Axes.Color(formsPlot2.Plot.Axes.Right, sig2.Color);
        formsPlot2.Plot.Axes.Color(formsPlot2.Plot.Axes.Top, sig2.Color);
        formsPlot1.Plot.HideGrid();

        // when one plot changes update the other plot
        formsPlot1.Plot.RenderManager.AxisLimitsChanged += (s, e) => PlotsToCopy = (formsPlot1, formsPlot2);
        formsPlot2.Plot.RenderManager.AxisLimitsChanged += (s, e) => PlotsToCopy = (formsPlot2, formsPlot1);

        // setup a timer to manage refreshes
        RefreshTimer.Interval = 10;
        RefreshTimer.Tick += (s, e) => CopyLimits();
        RefreshTimer.Start();
    }

    private (IPlotControl from, IPlotControl to)? PlotsToCopy = null;

    private void CopyLimits()
    {
        if (PlotsToCopy is null)
            return;
        (IPlotControl source, IPlotControl target) = PlotsToCopy.Value;
        AxisLimits limits1 = source.Plot.Axes.GetLimits(source.Plot.Axes.Bottom, source.Plot.Axes.Left);
        AxisLimits limits2 = source.Plot.Axes.GetLimits(source.Plot.Axes.Top, source.Plot.Axes.Right);
        target.Plot.Axes.SetLimits(limits1, target.Plot.Axes.Bottom, target.Plot.Axes.Left);
        target.Plot.Axes.SetLimits(limits2, target.Plot.Axes.Top, target.Plot.Axes.Right);
        target.Refresh();
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/cfb037d7-e58d-4877-b3c3-04040bd89b3f)

**Comment by rubenslkirchner** [comment] 2024-04-26 12:54
The user is expecting that when zoomed on the left and right axis ALL series will increase or decrease and not just the series that are linked to the axis. Same thing for the top and bottom axes.

**Comment by rubenslkirchner** [comment] 2024-04-26 13:48
Even version 5.0.29 has the same issue. The user was expecting that when scrolling on the Y axis, ALL series would change vertically. In the print I'm sending, notice that only the series in blue is changing the zoom.

![trips playback plotters scottplot_RvVVXh3NmK](https://github.com/ScottPlot/ScottPlot/assets/7251969/5c9f8040-3fa3-42fb-b288-cd8d9395c6eb)

**Comment by swharden** [comment] 2024-04-26 14:08
Ah, I understand the disconnect. Let me re-state your description of the issue:

"The user was expecting that when scrolling on the LEFT Y axis, the RIGHT Y axis would also change"

This is not the default behavior. The axis system was designed so whatever axis the cursor is over is the one that will be adjusted. However, I'm sure we can come up with a way to modify your code to achieve the functionality you're looking for. I'll re-open this issue as a reminder to revisit it later today and update you with the solution I come up with.

**Comment by swharden** [comment] 2024-04-26 14:11
... quick idea in case you want to try this before I get to it, the last code sample I shared could be modified to evaluate "what percent the axis limits changed after copying", then you could call SetAxisLimits to change the other axis could be changed by that same percentage.

**Comment by swharden** [comment] 2024-04-26 14:15
```cs
bool leftAxisChanged = /* calculate this */
bool rightAxisChanged = /* calculate this */

if (leftAxisChanged){
    double fractionLeftAxisChanged = /* calculate this */
    formsPlot1.Plot.Axes.Right.Range.ZoomFrac(fractionLeftAxisChanged);
}

if (rightAxisChanged){
    double fractionRightAxisChanged = /* calculate this */
    formsPlot1.Plot.Axes.Left.Range.ZoomFrac(fractionRightAxisChanged);
}
```

**Comment by swharden** [comment] 2024-04-26 23:22
Trying to implement this myself and it's getting pretty dicey with all the logic checks. I'll see about adding a flag that enables behavior like "if the left axis changes, change the right axis by the same fractional amount".

Interestingly this feature is unrelated to multi-axis plots. This is the sample code I'm starting with

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        var sig1 = formsPlot1.Plot.Add.Signal(Generate.Sin());
        sig1.Axes.YAxis = formsPlot1.Plot.Axes.Left;
        formsPlot1.Plot.Axes.Color(sig1.Axes.YAxis, sig1.Color);

        var sig2 = formsPlot1.Plot.Add.Signal(Generate.Cos());
        sig2.Axes.YAxis = formsPlot1.Plot.Axes.Right;
        formsPlot1.Plot.Axes.Color(sig2.Axes.YAxis, sig2.Color);
    }
}
```

![spbefore](https://github.com/ScottPlot/ScottPlot/assets/4165489/8bf2166e-817b-4258-b5e9-4ae6255155a1)

**Comment by swharden** [comment] 2024-04-26 23:28
Logic blocks like this here are the offending code:

https://github.com/ScottPlot/ScottPlot/blob/01fd7c8531c7eaf8c8e13fd5c974540a9235f605/src/ScottPlot5/ScottPlot5/Control/StandardActions.cs#L108-L114

Modifying it a bit we start to observe the OP's desired behavior

![spafter](https://github.com/ScottPlot/ScottPlot/assets/4165489/e78471b5-9229-4a89-8aca-41d12b533782)

**Comment by swharden** [comment] 2024-04-26 23:56
This feature will be in the next release as an opt-in feature:

```cs
formsPlot1.Interaction.ChangeOpposingAxesTogether = true;
```

![spafter3](https://github.com/ScottPlot/ScottPlot/assets/4165489/940c4d07-7d0d-46f8-a06a-11b6ec2c42d0)

**Closed** 2024-04-27 00:20 UTC
Labels: ⚠️ HIGH PRIORITY

**Comment by rubenslkirchner** [comment] 2024-04-29 10:55
Scott, this new configuration was perfect! Thank you very much for your efforts!!!
