### ISSUE TITLE
Vertical Tick labels with new lines render on top of each other

### ISSUE THREAD

**Issue by aespitia** [ScottPlot/ScottPlot#3673] opened 2024-04-16 20:36 UTC
Vertical Tick labels with new lines render on top of each other.

ScottPlot Version: 5.0.26

```cs
ScottPlot.Plot myPlot = new();

myPlot.Add.Bar(position: 1, value: 5);
myPlot.Add.Bar(position: 2, value: 7);
myPlot.Add.Bar(position: 3, value: 6);
myPlot.Add.Bar(position: 4, value: 8);

Tick[] ticks =
{
	new(1, "Apple\nNewLine\nGoes here"),
	new(2, "Orange"),
	new(3, "Pear"),
	new(4, "Banana"),
};

myPlot.Axes.Bottom.TickGenerator = new ScottPlot.TickGenerators.NumericManual(ticks);
myPlot.Axes.Bottom.MajorTickStyle.Length = 0;
myPlot.Axes.Bottom.TickLabelStyle.Rotation = 90;
myPlot.HideGrid();

// tell the plot to autoscale with no padding beneath the bars
myPlot.Axes.Margins(bottom: 0);

myPlot.SavePng("demo.png", 400, 300);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/105309364/f470780e-cc41-4d80-88a8-ec524f1d9fc8)

**Comment by swharden** [comment] 2024-04-16 22:31
At first I thought this was a multiline label rendering problem, but apparently not...


```cs
ScottPlot.Plot myPlot = new();

for (int i = 0; i <= 90; i += 45)
{
    var txt1 = myPlot.Add.Text($"Multiline\nRotated{i}", i, 0);
    txt1.LabelRotation = i;
    txt1.LabelFontSize = 26;
}

myPlot.HideGrid();
myPlot.SavePng("demo.png", 400, 300).LaunchFile();
```

![demo](https://github.com/ScottPlot/ScottPlot/assets/4165489/e98ed67b-35d9-4bf4-a61c-d3dbe2065d67)

**Comment by swharden** [comment] 2024-04-16 22:37
Ah, I think the issue is that the ticks are using less advanced logic for rendering multi-line strings. I bet we can leverage the `Render()` logic inside the `TickLabelStyle` class to fix this. I'll look further into that now! 

Here's a code example showing the core problem: multiline tick labels are always assumed to be horizontal text, so each line is "below" the one above it.

```cs
ScottPlot.Plot myPlot = new();

ScottPlot.TickGenerators.NumericManual tickGen = new();
tickGen.AddMajor(1, "Apple\nNewLine\nGoes here");
tickGen.AddMajor(2, "Orange");
tickGen.AddMajor(3, "Pear");
tickGen.AddMajor(4, "Banana");

myPlot.Axes.Bottom.TickGenerator = tickGen;
myPlot.Axes.Bottom.TickLabelStyle.Rotation = 45;
myPlot.Axes.Bottom.TickLabelStyle.FontSize = 26;
myPlot.Axes.Bottom.MinimumSize = 150;

myPlot.Axes.SetLimitsX(0, 5);
myPlot.SavePng("demo.png", 400, 300).LaunchFile();
```

![demo](https://github.com/ScottPlot/ScottPlot/assets/4165489/57a1e83d-a60a-4d30-bfc7-de41696e9b8b)

**Comment by swharden** [comment] 2024-04-17 00:15
I got to the bottom of this one and am about to merge a fix for this specific issue. 

There's a larger issue where rotated labels aren't respecting the vertical component of alignment (#3675) and fixing that should make this look nicer.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/3aac4d19-f91e-4654-a7d8-35bbc2a9605f)

**Closed** 2024-04-17 00:16 UTC
Labels: ⚠️ HIGH PRIORITY

**Comment by swharden** [comment] 2024-04-17 14:11
haha, good catch! Multiline labels are the gift that keeps on giving 😅 😅 😅
