### ISSUE TITLE
Y axis ticks drawn under X axis horizontal level

### ISSUE THREAD

**Issue by LeDahu22** [ScottPlot/ScottPlot#4256] opened 2024-09-12 14:02 UTC
**Issue:**  
Hi !

I'm trying to set the start level of my Y ticks at -0.5 using the following code : 
`plot.Axes.Left.Min = -0.5f;`

When trying to use this code outside of the RenderManager.RenderStarting event, it doesn't produce any change.

When using this code inside RenderManager.RenderStarting event, it works but ticks are also drawn under the X axis level. 

![image](https://github.com/user-attachments/assets/76b5aca4-d150-4329-88c6-59be3f80fa6c)

It looks kind of similar to the following issue : [https://github.com/ScottPlot/ScottPlot/issues/3889](#3889)

**ScottPlot Version:** 5.0.39

**Code Sample:** 

```cs
List<IGrouping<string, OverlappingVisitDto>> groups = list.GroupBy(x => x.LineName).ToList();

using(Plot plot = new Plot())
{
    PixelPadding padding = new(100, 50, 100, 100);
    plot.Layout.Fixed(padding);
    plot.Title("Overlapping visit percentage", 24);

    plot.Axes.Bottom.MinimumSize = 85;
    plot.Axes.Right.MinimumSize = 25;

    plot.Axes.Left.Label.Text = "Pourcentage";
    plot.Axes.Left.Label.Bold = true;

    plot.Grid.MajorLineColor = Colors.Green.WithOpacity(.3);
    plot.Grid.MajorLineWidth = 1;

    plot.Grid.MinorLineColor = Colors.Gray.WithOpacity(.3);
    plot.Grid.MinorLineWidth = 1;

    DateTimeXAxis dtAx = plot.Axes.DateTimeTicksBottom();
    plot.Axes.Bottom.TickLabelStyle.Rotation = 75;

    dtAx.TickGenerator = new DateTimeFixedInterval(
          new Day(),
          intervalsPerTick: 7,
          getIntervalStartFunc: dt => new DateTime(dt.Year, dt.Month, dt.Day)
    );

    plot.RenderManager.RenderStarting += (s, e) =>
    {
        Tick[] ticks = plot.Axes.Bottom.TickGenerator.Ticks;
        for(int i = 0; i < ticks.Length; i++)
        {
            DateTime date = DateTime.FromOADate(ticks[i].Position - 1);
            string label = $"{ISOWeek.GetYear(date)} S{ISOWeek.GetWeekOfYear(date).ToString().PadLeft(2, '0')}";
            ticks[i] = new Tick(ticks[i].Position - 1, label);
        }

        plot.Axes.Bottom.MajorTickStyle.Length = 10;
        plot.Axes.Bottom.MajorTickStyle.Width = 3;
        plot.Axes.Bottom.MajorTickStyle.Color = Colors.Black;

        plot.Axes.Bottom.TickLabelStyle.ForeColor = Colors.Red;
        plot.Axes.Bottom.TickLabelStyle.Bold = true;
        plot.Axes.Bottom.TickLabelStyle.OffsetY = 35;
    };

    Legend legend = plot.Legend;
    legend.Alignment = Alignment.UpperRight;
    legend.FontSize = 24;

    foreach(IGrouping<string, OverlappingVisitDto> line in groups)
    {
        DateTime[] xs = line.Select(l => l.FirstDate).ToArray();
        decimal[] ys = line.Select(l => l.Percentage).ToArray();

        Scatter sp = plot.Add.Scatter(xs, ys);
        sp.LegendText = line.Key;
    }

    string path = Path.Combine(Path.GetTempPath(), $"Result.png");
    plot.SavePng(path, 1587, 1123);
    filePaths.Add(path);
}
```

Here is the OverlappingVisitDto class : 

```cs
public sealed class OverlappingVisitDto
{
    public DateTime FirstDate { get; set; }

    public string CategoryName { get; set; } = null!;

    public decimal Percentage { get; set; }

    public OverlappingVisitDto()
    {

    }
}
```

FirstDate = first date of each week (starting on Monday)
"list" is just a `List<OverlappingVisitDto>`

Thank you for your help, and also for this awesome library ! 👍

**Comment by swharden** [comment] 2024-11-08 17:50
HI @LeDahu22, this is an overwhelming complex code sample which is probably why this issue hasn't had any feedback so far. Here's a simpler code sample that shows a result that appears to be working in a console application.

```cs
using ScottPlot;

Plot plot = new();

PixelPadding padding = new(100, 50, 100, 100);
plot.Layout.Fixed(padding);

DateTime[] dates = Generate.ConsecutiveDays(100);
double[] values = Generate.RandomWalk(100);
plot.Add.Scatter(dates, values);

plot.Axes.DateTimeTicksBottom();

plot.SavePng("result.png", 600, 400).LaunchFile();
```

![result](https://github.com/user-attachments/assets/d45767ba-7053-4848-8eda-dc8beaae0370)

Can you reproduce your problem by modifying the code above, ideally only editing a line or two?

Since I'm struggling to recreate this issue I'll close this thread, but I'm happy to open it up again if we have a simpler starter point to work from to find a solution. Thanks!

**Comment by swharden** [comment] 2024-11-08 17:51
```cs
DateTime date = DateTime.FromOADate(ticks[i].Position - 1);
```

**Closed** 2024-11-08 17:52 UTC

**Comment by LeDahu22** [comment] 2024-12-10 15:05
Hi @swharden 
Apologies for the late answer, I've been able to find the culprit :

Setting the following line allows to recreate the issue : plot.Layout.Fixed(padding);

If you comment it, the left axes starts at 0 (as expected)

```
using ScottPlot;
using ScottPlot.AxisPanels;
using System.Globalization;

Plot plot = new();

PixelPadding padding = new(100, 50, 100, 100);
plot.Layout.Fixed(padding);

DateTime[] dates = Generate.ConsecutiveDays(100);
double[] values = Generate.RandomWalk(100);
plot.Add.Scatter(dates, values);

DateTimeXAxis dtAx = plot.Axes.DateTimeTicksBottom();
plot.Axes.Bottom.TickLabelStyle.Rotation = 90;

plot.RenderManager.RenderStarting += (s, e) =>
{
    Tick[] ticks = plot.Axes.Bottom.TickGenerator.Ticks;
    for (int i = 0; i < ticks.Length; i++)
    {
        DateTime date = DateTime.FromOADate(ticks[i].Position - 1);
        string label = $"{ISOWeek.GetYear(date)} S{ISOWeek.GetWeekOfYear(date).ToString().PadLeft(2, '0')}";
        ticks[i] = new Tick(ticks[i].Position - 1, label);
    }

    plot.Axes.Bottom.TickLabelStyle.OffsetY = 35;
    plot.Axes.Left.Min = 0;
};

plot.SavePng("result.png", 800, 600).LaunchFile();
```

Thank you !
