### ISSUE TITLE
Problems about scatter smooth:

### ISSUE THREAD

**Issue by Liwr9537** [ScottPlot/ScottPlot#4554] opened 2024-11-24 02:13 UTC
Recently, I encountered a problem when using the Smooth property of scatter plot. It seems that the smooth will break down when there are two or more points very close to each other compared to other points in the diagram. So, I'd appreciate that if someone could tell me how to solve this problem. Or maybe there are some problems with the smoothing algorithm?

ScottPlot Version: 5.0

Here are some screenshots about the smooth problem:
![problem2](https://github.com/user-attachments/assets/30744f59-9b98-484b-8de3-6acf0579c248)
![problem3](https://github.com/user-attachments/assets/08172412-d3fc-488d-a3bc-f9b7d50c6817)

Thanks!

**Comment by swharden** [comment] 2024-11-24 14:50
Hi @Liwr9537, thanks for sharing this issue! This is a known "problem" when using Bezier splines to draw smooth curves between collections of points. I put "problem" in quotes because this is the intended behavior of Bezier splines, and the issue here is that Bezier splines may not be the best logic to use to show smooth lines between your data points.

Check out the following cookbook recipes, especially the third one. There are other path smoothing strategies beside Bezier curves. If you're not satisfied with the built-in ones, you can create your own and assign it to the `PathStrategy` property. If you end up creating one that is a better fit for your application, let us know and we can include it in future releases of ScottPlot!

* https://scottplot.net/cookbook/5.0/Scatter/ScatterSmooth/
* https://scottplot.net/cookbook/5.0/Scatter/ScatterSmoothTension/ (changing tension may help)
* https://scottplot.net/cookbook/5.0/Scatter/ScatterQuad/ (shows how to use another path smoothing strategy)

**Closed by swharden** 2024-11-24 14:50 UTC

**Comment by Liwr9537** [comment] 2024-11-24 15:05
That would be great. And I will have a try.
