### ISSUE TITLE
Resize: automatically zoom to fit data

### ISSUE THREAD

**Issue by noob765** [ScottPlot/ScottPlot#1197] opened 2021-08-08 22:33 UTC
In engineering, equal axes are a big deal to the point of often being a show stopper... and while describing the functionality provided here as 'wrong' might seem like hyperbole, the user experience falls short of what is provided by other packages (and implicitly, what is expected). 

First a demonstration of the issue:  Set any plot to EqualScaleMode.ZoomOut and the axes will be equal alright (so it's sort of the correct behavior), but testing user experience demands we go further. Grab the lower right corner of your window and drag it right, then down, then left, then up, then right... Keep doing this resizing the window one axis at a time and watch your plot shrink smaller and smaller until it becomes but a blip in the center of the screen surrounded by ever growing axes... Shrinking data as I shrink the plot? Yes. Same data size as I expand it? No! It should expand too! (that's the 'wrong' behavior, which is truly annoying).

After finally figuring out what properties represent what in there, and that DataSizePx is NOT the pixel size the data needs (which would make sense considering how it's used in EnforceEqualAxisScales() ), but in fact the max pixel size that data HAS available, the source of the problem became obvious.

In EnforceEqualAxisScales, the line
```cs
double num = Math.Max(XAxis.Dims.UnitsPerPx, YAxis.Dims.UnitsPerPx);
```
can't possibly use UnitsPerPx since it's determined using DataSizePx. Equal scaling must be determined considering what the data would actually need to get plotted at a given scale, not how much it has available.

The following is a hacked EnforceEqualAxisScales that uses C&P code from AxisAutoX/Y to determine data extents. It's ugly, it doesn't respect any kind of margins, but it works as expected:

```cs
  case EqualScaleMode.ZoomOut:
        double minX = double.NaN;
        double maxX = double.NaN;
        double minY = double.NaN;
        double maxY = double.NaN;
        int xAxisIndex = 0;
        int yAxisIndex = 0;

        var plottableXLimits = Plottables.Where(x => x is IPlottable)
                                           .Select(x => (IPlottable)x)
                                           .Where(x => x.IsVisible)
                                           .Where(x => x.XAxisIndex == xAxisIndex)
                                           .Select(x => x.GetAxisLimits())
                                           .ToArray();

        foreach (var limits in plottableXLimits)
        {
            if (!double.IsNaN(limits.XMin))
                minX = double.IsNaN(minX) ? limits.XMin : Math.Min(minX, limits.XMin);
            if (!double.IsNaN(limits.XMax))
                maxX = double.IsNaN(maxX) ? limits.XMax : Math.Max(maxX, limits.XMax);
        }

        var plottableYLimits = Plottables.Where(x => x is IPlottable)
                                           .Select(x => (IPlottable)x)
                                           .Where(x => x.IsVisible)
                                           .Where(x => x.YAxisIndex == yAxisIndex)
                                           .Select(x => x.GetAxisLimits())
                                           .ToArray();

        foreach (var limits in plottableYLimits)
        {
            if (!double.IsNaN(limits.YMin))
                minY = double.IsNaN(minY) ? limits.YMin : Math.Min(minY, limits.YMin);
            if (!double.IsNaN(limits.YMax))
                maxY = double.IsNaN(maxY) ? limits.YMax : Math.Max(maxY, limits.YMax);
        }

        if (double.IsNaN(minX) && double.IsNaN(maxX))
            return;
        if (double.IsNaN(minY) && double.IsNaN(maxY))
            return;

        double maxUnitsPerPx = Math.Max((maxX - minX) / XAxis.Dims.DataSizePx, (maxY - minY) / YAxis.Dims.DataSizePx);
        double halfX = (XAxis.Dims.DataSizePx / 2) * maxUnitsPerPx;
        double halfY = (YAxis.Dims.DataSizePx / 2) * maxUnitsPerPx;
        AxisSet(XAxis.Dims.Center - halfX, XAxis.Dims.Center + halfX, YAxis.Dims.Center - halfY, YAxis.Dims.Center + halfY);
        return;
```
The point is, it finds the actual data extents, and FROM THAT figures out the axes scaling (and the data shrinks and grows as needed). I didn't check since these modes are useless to me, but looking at the code I suspect PreserveX/Y suffer from the same issues...

...I'm also thinking a dedicated method to find data extents might be in order (I was a bit surprised there wasn't one). Given how often this code has to run with equal axes on (again, it's a big deal), performance might even benefit from computing extents on Add/Update and having it readily available when needed instead of having to go through the list of plottables on every render... though that might be an architectural change.

* **ScottPlot Version:** 4.1.16
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 5.0

**Comment by swharden** [comment] 2021-08-25 01:06
Hi @noob765, thank you for opening this issue and providing useful insight!

## Expectation

> In engineering, equal axes are a big deal to the point of often being a show stopper... and while describing the functionality provided here as 'wrong' might seem like hyperbole, the user experience falls short of what is provided by other packages (and implicitly, what is expected).

This is new information to me! My background is in dentistry and biology, and my choice of the phrase "equal axes" to describe this functionality was coincidental. It's helpful to know this is an established term in the engineering world, so refining the language of the API (and XML docs) to clearly describe what it does or change its behavior to meet expectation seems worth it.

## Demonstrating the Issue

> First a demonstration of the issue: Set any plot to EqualScaleMode.ZoomOut and the axes will be equal alright (so it's sort of the correct behavior), but testing user experience demands we go further. Grab the lower right corner of your window and drag it right, then down, then left, then up, then right... Keep doing this resizing the window one axis at a time and watch your plot shrink smaller and smaller until it becomes but a blip in the center of the screen surrounded by ever growing axes... Shrinking data as I shrink the plot? Yes. Same data size as I expand it? No! It should expand too! (that's the 'wrong' behavior, which is truly annoying).

Similar to #1171 I am having trouble understanding what your expectation is and how it differs from what you observe. If you use a non-standard lock behavior (one that always zooms out axes to enforce equal scales), isn't this the expected behavior?

Instead of doing a lot of right-click-drag actions, I think the same effect is achieved by dragging the corner of the window. This issue/misunderstanding may be related to #857

### Default Behavior

```cs
double[] xs = { -10, 10, 10, -10 };
double[] ys = { -10, -10, 10, 10 };
formsPlot1.Plot.AddPolygon(xs, ys);
formsPlot1.Plot.AxisScaleLock(enable: true); // default behavior
```

![mode-default](https://user-images.githubusercontent.com/4165489/130709568-d8de0f1f-8856-4f77-b41e-7e82128a541f.gif)

### Only Zoom Out Behavior

```cs
double[] xs = { -10, 10, 10, -10 };
double[] ys = { -10, -10, 10, 10 };
formsPlot1.Plot.AddPolygon(xs, ys);
formsPlot1.Plot.AxisScaleLock(enable: true, EqualScaleMode.ZoomOut); // alternate behavior (always zoom out)
```

![mode-zoomout](https://user-images.githubusercontent.com/4165489/130709557-85ed8b01-d2e7-435d-ad22-e147b6d5838a.gif)

**Comment by noob765** [comment] 2021-08-25 02:03
First, how do you make them animations??? (sorry if that's obvious but I missed class that day)

Yeah, to each his own field I guess ;) I took the hardcore mechanical engineering track and in that field specifically, equal axes are a thing. Think about it: most of what we do is about physics and spatial relationships so plotting force diagrams or simulation results on physical objects is a daily event. The exact problem I'm on these days is an optical element (lens) manufacturing software for our factories around the world. The main interface is a cross-section plot of the lens **to scale**. Not only does it have to look right, but it has to be right for our guys to have the ability to evaluate if we can make what the customers are asking for, if surface curvatures are within machine tolerances, if machine tool clearances are enough not to break anything (we're talking about million dollar machines that go far below submicron levels). I have a ton of code that checks everything on an analytical level but the one thing you never want to do is leave the guy that's been doing this for 30 years out of the loop. That's where equal axes plots come in...

I really wouldn't say there's an accepted 'engineering term' here, or that you've abused the term in any way. I mean, equal axes are pretty much what they say they are: equal. If I plot a square, I want a square. 

That said, here's another little bit of information that might be new to you: us engineers are experts at breaking shit, for real. The only way to design anything reliable is to know how to break them. Please read this picturing me with a big smile without any ill intent but... when you test stuff, you have to test with the intent of breaking them. Otherwise you're just demonstrating functionality, which is a whole other thing. That's what your animations are doing above.

If you take the default case {AxisScaleLock(enable: true)}, it looks fine, only because you're constraining yourself to the behavior that looks fine. My understanding is that default is actually PreserveY, so let's test... for real. Drag the corner all the way up and the square shrinks. Good, that's what I'm expecting. Now drag the window all the way left, and you'll see the square spill over the sides of the graph without shrinking: BAD! I'm expecting the square to shrink again so that I keep seeing it all. So PreserveY (or Default) is no good here.

Let's go to ZoomOut then. No need to explain anything here, the behavior I talked about is what you have above in your animation...

So the problem is exactly what your second animation shows. Getting a productivity tool to be accepted by the pros while having that behavior is asking for a lot. It should shrink and grow as required to fill the space while maintaining equal scaling. A secondary problem is that you're not testing like you're an actual user... and no user will be so kind as to always keep that square in full view like you are above. That's why you have trouble seeing the problem.

Again, this is meant in the nicest most helpful possible way... (I'm really not here to bully anyone)

**Comment by swharden** [comment] 2021-08-25 03:10
> how do you make them animations?

https://www.screentogif.com is awesome 🤩 

> we're talking about million dollar machines that go far below submicron levels

It's always cool to see what people use ScottPlot for! I'm on the consumer end of fancy optics. My profile pic http://github.com/swharden.png has a laser-scanning two-photon fluorescent microscope behind me 🤓 

> when you test stuff, you have to test with the intent of breaking them. Otherwise you're just demonstrating functionality, which is a whole other thing. That's what your animations are doing above.

Your point is very well-received!

I'm not particularly an Elon Musk fan, but I recall a quote something to the effect of, "if you didn't blow up a rocket during testing, it's because you didn't test it hard enough"

For what it's worth I don't think this is a testing issue. I think this is a communication/expectation issue. As we'll explore in the following paragraph, I think you and I simply expected different things to happen when you drag a shape toward the edge of the screen. Computers are easy - people are hard 🙃 

## Demonstrating Current Behavior

> If you take the default case {AxisScaleLock(enable: true)}, it looks fine, only because you're constraining yourself to the behavior that looks fine. My understanding is that default is actually PreserveY, so let's test... for real. Drag the corner all the way up and the square shrinks. Good, that's what I'm expecting. Now drag the window all the way left, and you'll see the square spill over the sides of the graph without shrinking: BAD! I'm expecting the square to shrink again so that I keep seeing it all. So PreserveY (or Default) is no good here.

```cs
double[] xs = { -10, 10, 10, -10 };
double[] ys = { -10, -10, 10, 10 };
formsPlot1.Plot.AddPolygon(xs, ys);
formsPlot1.Plot.AxisScaleLock(enable: true);
```

![mode-2](https://user-images.githubusercontent.com/4165489/130718507-9953061c-8561-45f3-bd31-9613ca2b8578.gif)

## Expected vs. Actual Functionality

Notice the description of what this method does:

https://github.com/ScottPlot/ScottPlot/blob/22b9bad0aeaf66783c6bc8ae63e8c73124f453d1/src/ScottPlot/Plot/Plot.Axis.cs#L484-L489

The intent of this method is to protect symmetry of objects. 

The intent is _not_ to also "recognize where objects are located relative to the current view limits and adjust the axis limits as needed to ensure all edges of all objects are continuously within the field of view". 

I don't intend to implement such behavior, but to give it a name let's call it `DisallowDataClipping()`.

Notice that disallowing data clipping could be done with but also without enforcing equal X/Y scales. These are fundamentally different problems, although I recognize your use case involves engaging both at the same time.

> Now drag the window all the way left, and you'll see the square spill over the sides of the graph without shrinking: BAD! I'm expecting the square to shrink again so that I keep seeing it all.

Back to the original issue, I think this is just a mismatch in expectation.

## Is it possible to disallow data clipping?

Maybe. 

There is a very similar function `SetViewLimits()` which prevents the user from zooming out beyond the defined values. Perhaps this could be split into two methods, one to set maximum limits and one to set minimum limits. If you set your minimum limits to the boundaries of your data, you may achieve the functionality you're looking for with this issue.

Can data limits be detected automatically? No. One of the reasons ScottPlot can be so fast is that it works on raw arrays that users are permitted to modify in real time (https://swharden.com/scottplot/faq/live-data) including from multi-threaded applications. To do this in real time you'd have to check data limits before every rendered frame, and this is impractical when plots contain tens of millions of points. There are also issues related to moving the axis limits around _while_ the mouse is click-dragging.

I'll leave this issue open to explore what could be done to extend `SetViewLimits()` to also support minimum limits instead of only maximum limits.

---

> Again, this is meant in the nicest most helpful possible way... (I'm really not here to bully anyone)

No worries! Same here. I took a long time to get to #1197 and #1171 because I've been trying to clear-out all the open PRs/issues in preparation for a huge one (#1036), and I pushed-off this one because it seemed so complex.

Let me know if I captured our misunderstanding, and what you think about my possible solution (and potential alternative naming?) I'm interested in hearing your thoughts!

Scott

**Comment by noob765** [comment] 2021-08-25 04:00
Your animation is not exercising the problem: I'm not referring to panning which is fine (what you're doing), but always to figure resizing (your previous reply). Your previous animations were correct, just not extreme enough. 

> The intent is not to also "recognize where objects are located relative to the current view limits and adjust the axis limits as needed to ensure all edges of all objects are continuously within the field of view".

If you're talking about panning, I agree, it works fine as is. If I drag the *content* out of frame, it's because I want it out of frame.

But as far as figure resizing is concerned, let me be clear: this HAS to be an intent. Period. Otherwise I take back what I said and the term 'equal axes' is abused and will mislead everyone coming across it for very simple reasons: it's what every other package does. And we're back to my original comment about user experience and expectations already in place due to said experience: it's what everyone is used to, and what is considered sensible behavior.

The reasoning is, if I pan a plot off frame, it's my intent. Just get out of the way. But if I resize said frame then my intent is *not* to change the nature of the information shown but merely to reorganize my real estate. The information (ie, the plot content shown) has to stay the same within the constraints set prior to the resize. Not doing so is a flagrant violation of the principle of least astonishment and users will hate you for it (even more so that they've been worn down to expect something else). If I had the plot set to autoscale (so shown in its entirety) *and* I happen to have said plot to have equal axes *and* I resize *in any direction, to any ratio*, then I'm fully expecting the content (so everything) so stay in view with equal scales. Here that means if I resize vertically, the plot shrinks, if I resize laterally, the plot shrinks. Either way, I keep seeing it all because in resizing I never had any intent to change that information. And if I resize my frame bigger after, the content grows, always so it takes whatever real estate it needs so the shown content stays the same.

My very first post highlights what's needed here: every time an equal axes rescale is done, it has to be done in relation to data content extents so the axes are scaled relative to what the data needs and not what it's taking at the moment of the resize. It's not necessarily a trivial change in the context of margins and all but it's essential, at least to claim a commonly accepted functionality of 'equal axes'. 

Facing the possibility that I wouldn't have an adequate plotting framework, I've started to roll my own after filing 1171. I have to thank you for the help: your online material and this toolset have given me a head start in the right direction. But one major difference is pretty clear now: I baked in equal axes from the start. Free axes are a just loose generalization of equal axes scaling... and the structure of my stuff is really not the same as yours (one big deal is data extents auto updating as stuff is added removed and moved around. It's essential for all scaling operations).

**Comment by EmanuelFeru** [comment] 2021-08-28 09:24
Hi @noob765 with axislock on, personally I see no issue in the behavior you show. That for me is the expected behavior. Can you be more precise in what are you still missing? What do you mean by "the scaling that ignores data extents"?

**Comment by noob765** [comment] 2021-08-28 10:06
Again, I did say what I show above is MY OWN CODE, meaning NONE OF IT is using ScottPlot at all, only my own home brewed code I'm developing for the task. That's why you don't see any issue. That said, I can't claim to know every trick there is with ScottPlot itself so it very well might be that I don't understand the inner workings enough to get it to behave.

So let's spin this around: show me the specific ScottPlot code that replicates exactly all of the behavior I'm showing above. If you succeed then all is well and I'll learn something. If you fail, then that should tell you where the problem is...

**Comment by swharden** [comment] 2021-08-29 23:10
Hi @noob765, thanks for your additional clarification! The screen capture you shared was very helpful.

## Restating the Problem

When you ***resize*** a ScottPlot window, data may fall off the edge. 

Current behavior is unrelated to axis scale lock - it happens the same whether the scales are locked or not.

![noob5](https://user-images.githubusercontent.com/4165489/131267687-7f36069e-6397-43b6-9caf-2c3f1b1220b6.gif)

@noob765 would prefer the plot to automatically detect if data is about to fall off the edge while ***resizing*** and automatically ***zoom*** so all the data remains in the data area. Their example is:
![noob4](https://user-images.githubusercontent.com/4165489/131267704-883f62db-4142-4f67-b30d-206bfaf91c1e.gif)

PS: tick rendering/placing is poor when axis scale lock is enabled. I'll track that in #1129

## Lesson Learned

There has been a lot of text discussion, code samples, and general time investment through this point in this thread and also all of #1171, and only today was the problem statement adequately communicated such that I could understand it. I accept much of the responsibility for not being able to interpret your messages well enough to understand the problem (although @EmanuelFeru was confused by it too), but this is an important reminder that discussing technical aspects of fixes, implementation details, and even diving into code modifications (#1171) is ***grossly premature** if the problem can't be adequately defined such that it is understood by all parties. 

In public codebases where discussion is limited to text and many contributors are not native English speakers, this experience was a good reminder that effective communication is difficult.

## Possible Fixes

These fixes could be used with or without axis scale lock.

It sounds like @noob765 has made progress toward a solution for their own application, but it's worth considering whether these options are worth adding to this library. I'll continue to explore these options:

### Auto-Fit on every frame
It's impractical to automatically detect limits of the data _while_ zooming or resizing for most applications. Iterating arrays with tens of millions of points to perform min/max calculations would be a big performance hit. However, this functionality could be implemented and disabled by default.

### Minimum Zoom Area
This option was discussed above. The user could define a bounding box in coordinate space beyond which the user cannot zoom in. The compliment (a zoom-out limit) is already implemented. The upside is there is no performance hit, but the downside is that the user would be responsible for defining the limits.

**Comment by swharden** [comment] 2021-08-31 23:44
> No clue about Python though 

Default resizing behavior seems to be the effect you're recommending here
```python
import matplotlib.pyplot as plt
xs = [-10, 10, 10, -10, -10]
ys = [-10, -10, 10, 10, -10]
plt.plot(xs, ys, '.-', lw=5, ms=20)
plt.grid(alpha=.5, ls='--')
plt.gca().axis('equal')
plt.show()
```
![mpl](https://user-images.githubusercontent.com/4165489/131589116-1da2144c-b5b3-4636-907c-6c5afac4ba47.gif)

**Comment by swharden** [comment] 2021-09-01 00:06
## Python/Matplotlib Resize Behavior

>> No clue about Python though

> Default resizing behavior seems to be the effect you're recommending here

Actually I was mistaken. That was a coincidental effect of having the data in the center of the figure. When the data is offset, it looks like matplotlib allows it to fall off the edge.

Interesting to note that "preserving X scale" or "preserving Y scale" is a function of whether the plot is wider than high or not. This is probably worth implementing in ScottPlot.

```cs
import matplotlib.pyplot as plt
xs = [-10, 10, 10, -10, -10]
ys = [-10, -10, 10, 10, -10]
plt.plot(xs, ys, '.-', lw=5, ms=20)
plt.grid(alpha=.5, ls='--')
plt.gca().axis('equal')
plt.show()
```

![mpl2](https://user-images.githubusercontent.com/4165489/131590617-7a09f446-3764-4cc2-af45-094a4c4718ca.gif)

## A custom control is probably the way to go

> Facing the possibility that I wouldn't have an adequate plotting framework, I've started to roll my own after filing #1171

Sounds like you're well on your way!

> ...taking hints from what's around is never a bad thing. But these days, if you're going for exact replication (of matlab/matplotlib for example), they're not exactly the model citizens that the forums will have you believe...

Good advice! I'll probably close this issue for now content to mimic matplotlib. 

Thanks again for all your insightful input above 👍

**Comment by swharden** [comment] 2021-09-01 01:29
> [regarding Python's default behavior] Interesting to note that "preserving X scale" or "preserving Y scale" is a function of whether the plot is wider than high or not. This is probably worth implementing in ScottPlot.

@noob765 I did this 23a265d and to my surprise it resulted in the behavior you were seeking for all along! Problem solved?

![sp3](https://user-images.githubusercontent.com/4165489/131596976-4908f941-f81d-4693-9e75-48adcb627b75.gif)

**Closed** 2021-09-01 01:30 UTC
