### ISSUE TITLE
Default font renders incorrectly on Ubuntu Linux

### ISSUE THREAD

**Issue by Joe-Westra** [ScottPlot/ScottPlot#1220] opened 2021-08-22 23:27 UTC
## Bug Report

**Issue:** Incorrect characters on axis tick labels (see attached picture).  I have tried changing the font, which changes the amount of boxes shown, but cannot get tick labels as shown on the website examples.
![UNfiltered](https://user-images.githubusercontent.com/20119513/130373383-295aeb6e-a186-4343-811d-c50c4f6babe7.png)

**Reproducing:** Create a .NET 5 console application, create a basic plot and save it to disk.  Open saved file and examine the x and y axis ticks.  Box characters show up instead of values.

```cs
            //signal + noise
            double fs = 1000; //sampling rate
            double fw = 5; //signal frequency in hz
            double fn = 50; //noise frequency in hz
            double n = 10; //number of periods to show
            double A = 100; //signal amplitude
            double N = 10; //noise amplitude
            int size = (int)(n * fs / fw); //sample size

            var t = Enumerable.Range(1, size).Select(p => p * 1 / fs).ToArray();
            var y = t.Select(p => (A * Math.Sin(2 * Math.PI * fw * p)) + (N * Math.Sin(2 * Math.PI * fn * p))).ToArray();

            var bandpass = OnlineFirFilter.CreateBandpass(ImpulseResponse.Finite, fs, 0, 10);

            double[] bp = bandpass.ProcessSamples(y);

            double[] dataX = t;
            var plt = new ScottPlot.Plot(640, 480);
            plt.XAxis.TickLabelStyle(fontName: "Samanata", fontSize: 12);
            plt.YAxis.TickLabelStyle(color: Color.DarkBlue, fontName: "Meera", fontSize: 16);
            plt.AddScatter(t, brwide);
            plt.SaveFig("brwide.png");
```

### System Details
* **ScottPlot Version:** 4.1.16
* **Operating System:** Ubuntu Linux 20.04
* **Application Type:** console
* **.NET Version:** .NET 5.0

**Comment by bclehmann** [comment] 2021-08-23 23:56
I can replicate this on WSL, and it looks like this is a duplicate of #1079, also on [StackOverflow](https://stackoverflow.com/a/67729839/3513171). The solution is to explicitly install `System.Drawing.Common`.

**Comment by swharden** [comment] 2021-08-24 00:07
Hi @Joe-Westra, thanks for reporting this!

It looks like System.Drawing is having a hard time properly rendering text on your system.

## Code Sample

Unfortunately your code sample contains references to classes which are not described so I can't run your code sample on my end. Here's a simpler/reproducible program which works for me but may fail on your system:

```cs
using System;
using ScottPlot;
using System.Drawing;

var plt = new ScottPlot.Plot(400, 300);
plt.XAxis.TickLabelStyle(fontName: "Samanata", fontSize: 12);
plt.YAxis.TickLabelStyle(color: Color.DarkBlue, fontName: "Meera", fontSize: 16);
plt.SaveFig("westra.png");
```

![image](https://user-images.githubusercontent.com/4165489/130533293-3417243c-e1a5-45b1-8bdf-647bbe8e2e8e.png)

## Linux Font Names (and Typo?)

I think you're on the right track trying different font names.

I think `fc-list` will lists fonts on Ubuntu systems http://manpages.ubuntu.com/manpages/bionic/man1/fc-list.1.html

Have you tried several?

**Comment by swharden** [comment] 2021-08-24 00:50
> solution is to explicitly install System.Drawing.Common

Awesome @bclehmann, thanks for remembering that! 

I generated these images with Ubuntu 20.04.3 LTS (WSL)

Without System.Drawing.Common Installed | With System.Drawing.Common Installed
---|---
![image](https://user-images.githubusercontent.com/4165489/130537352-e21c4eed-c76b-4f56-932c-f25d97e4c412.png)|![image](https://user-images.githubusercontent.com/4165489/130537380-8a5d0ef6-c0f4-44e7-a1bf-c54f34a0e790.png)

## csproj Issue?

Any idea why System.Drawing.Common installed automatically when we `dotnet add package ScottPlot` on Linux?

https://github.com/ScottPlot/ScottPlot/blob/e7ababd235acc13979fbb9d4b9b60c5914e28eba/src/ScottPlot/ScottPlot.csproj#L33

It's listed as a dependency https://www.nuget.org/packages/ScottPlot

**Closed** 2021-08-24 00:59 UTC
Labels: BUG

**Comment by Joe-Westra** [comment] 2021-08-24 04:39
Awesome, thanks for the help!
