### ISSUE TITLE
WinForms: Demonstrate how to use ScottPlot inside a MDI container

### ISSUE THREAD

**Issue by woodynwc** [ScottPlot/ScottPlot#4415] opened 2024-10-31 23:25 UTC
**Issue:** Plot vanishes when a new MDI window is opened

**ScottPlot Version:** 5.0.34

**Code Sample:** 
Unfortunately my code is on a disconneted network... you know, security
Plot shows fine on the newest MDI window but vanishes on the prior one.

### Parent MDI form
```cs
form frm = new form(this);
frm.show();
frm.MdiParent = this;
```

### Child MDI form
```cs
public partial class frm : Form
{
   readonly FormsPlot fp = new FormsPlot();

  public frm()
  {   
     InitializeComponent();
     panel.Controls.Add(fp);
```

…. Basic code to create plot works fine …

Please slap me upside my head and tell me what I am missing, thanks ;^)

**Comment by swharden** [comment] 2024-10-31 23:38
Hi @woodynwc, 

It's a bit hard to evaluate what the issue is given the code provided. Could you create a blank new WinForms app and share the minimum code necessary to recreate this issue?

You may be surprised that in the process of creating that example, you may solve the problem 🙃 

Perhaps this code could help clarify the basic steps:
https://scottplot.net/faq/add-winforms-programmatically/

**Comment by swharden** [comment] 2024-10-31 23:39
Ah, I think this is the issue...

```cs
readonly FormsPlot fp = new FormsPlot();
```

You're missing the "full size dock" which makes it big. Otherwise without a defined pixel size I think it defaults to 0px by 0px which may be your issue. Assuming this is the case I'll close this ticket, but if you're still stuck let me know and we can open it back up and try again!

```cs
readonly FormsPlot FormsPlot1 = new FormsPlot() { Dock = DockStyle.Fill };
```

**Comment by woodynwc** [comment] 2024-10-31 23:44
Sorry, I should have included that in my example.  I do have that in my actual code.  When the first MDI form is created, it works fine.  The issue is that first MDI form plot area vanishes when I open a second MDI window.

**Comment by woodynwc** [comment] 2024-10-31 23:50
It is impossible at work to create a demo form due to my work situation on an air gapped network.  I will have to create a minimal one at home as you suggest to see how it behaves.

Thanks for your amazing product and support.

**Comment by swharden** [comment] 2024-10-31 23:55
> It is impossible at work to create a demo form due to my work situation on an air gapped network. I will have to create a minimal one at home as you suggest to see how it behaves.

Wow! It sounds like you're working on something fun 😎 

> Thanks for your amazing product and support

Sure thing! I'm interested in learning more about this topic 👍

**Comment by swharden** [comment] 2024-11-01 00:00
This should do it 🚀 

```cs
namespace WinFormsApp25;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
        this.IsMdiContainer = true;

        button1.Click += (s, e) =>
        {
            Form childForm = new() { MdiParent = this };
            ScottPlot.WinForms.FormsPlot FormsPlot1 = new() { Dock = DockStyle.Fill };
            FormsPlot1.Plot.Add.Signal(ScottPlot.Generate.RandomWalk(100));
            childForm.Controls.Add(FormsPlot1);
            childForm.Show();
        };
    }
}
```

![mdi](https://github.com/user-attachments/assets/8489b63a-a831-4ba5-902d-a5bb3a91a12e)

**Closed by swharden** 2024-11-01 00:00 UTC

**Comment by woodynwc** [comment] 2024-11-01 00:02
Wow, thanks.  I will take a look.

**Comment by swharden** [comment] 2024-11-01 00:13
Added this to https://scottplot.net/faq/mdi/

**Comment by woodynwc** [comment] 2024-11-04 19:25
Ok, it turned out that when my MDI form got resized, I was manually resizing the form which was causing it to vanish.  I just switched it to use the design time Anchor property which both worked and solved the vanishing issue.

Thanks for your support.
